### ISSUE TITLE
When using spacepy.coordinates.Coords, getting 'ImportError: cannot import name irbempylib'

### ISSUE THREAD

**Issue by johncoxon** [spacepy/spacepy#1]
I have installed spacepy 0.1.5 using `pip install spacepy` and then done `from spacepy import time as spt, coordinates as spc`. I attempt to create a `Coords` object by writing `my_gse_coords = spc.Coords(my_coords, 'GSE', 'car')`, where `my_coords` is a numpy array of shape (n, 3). Python fails on this line and I get an error: `ImportError: cannot import name irbempylib`. The full traceback is below.

	~/anaconda/lib/python2.7/site-packages/spacepy/coordinates.pyc in __init__(self, data, dtype, carsph, units, ticks)
		 77     def __init__(self, data, dtype, carsph, units=None, ticks=None):
		 78 
	---> 79         from . import irbempy as op
		 80         from spacepy.irbempy import SYSAXES_TYPES as typedict
		 81 

	~/anaconda/lib/python2.7/site-packages/spacepy/irbempy/__init__.py in <module>()
		 68 
		 69 
	---> 70 from .irbempy import *
		 71 

	~/anaconda/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py in <module>()
		 21 import spacepy.coordinates as spc
		 22 import spacepy.datamodel as dm
	---> 23 from . import irbempylib as oplib
		 24 import spacepy.toolbox as tb
		 25 

	ImportError: cannot import name irbempylib

Am I doing something wrong, or is this just a bug in spacepy?

**Comment by graingert** [comment]
I'm going to have to point you to https://sourceforge.net/p/spacepy/bugs/?source=navbar

My suspicion is that irbem failed to compile

https://github.com/spacepy/spacepy/blob/master/setup.py#L285

Not sure why there's a mix of relative and absolute imports there though...

**Comment by johncoxon** [comment]
Ah, I installed spacepy before I'd done anything with Fortran on my machine, so uninstalling and reinstalling did the trick. Thanks for the assist!
