### ISSUE TITLE
Typo in new issue template

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#101]
There is a typo in the code in the new issue template, I am not sure where these are stored or I would fix it. 

Right here:
```
import platform
import sys
import numpy
import scipy
import matplotlib

print(platform.platform())
print(sys.version_info)
print('numpy={0}'.formatnumpy.__version__))
print('scipy={0}'.format(scipy.__version__))
print('matplotlib={0}'.format(matplotlib.__version__))
```

Missing `(` after `format` in `print('numpy={0}'.formatnumpy.__version__))`.

**Comment by drsteve** [comment]
They're in the .github directory.
Feel free to fix and submit a PR.

**Comment by jtniehof** [comment]
I can't submit a PR, "There isn’t anything to compare. We couldn’t figure out how to compare these references, do they point to valid commits?" [https://github.com/spacepy/spacepy/compare/master...jtniehof:master](https://github.com/spacepy/spacepy/compare/master...jtniehof:master)

**Comment by jtniehof** [comment]
I'm not sure if there's something wrong with doing PR's off of personal master, but it's worked before and I didn't feel like farting around with making a branch, pushing a branch, deleting the branch... for a one character fix. I also wonder if it's confuzzled by being in a hidden directory.

**Comment by jtniehof** [comment]
And I've verified the parent of the commit I'm comparing has the same SHASum as spacepy/spacepy:master (14dc5165c344e8399faf0bbca571a94b052958a5)

**Comment by drsteve** [comment]
Given the potential trouble noted above I took the liberty of just doing the commit through the browser. I guess I could have committed direct to master, but for the sake of process I committed to a new branch.
