### ISSUE TITLE
pycdf slow close

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#110]
Large CDFs are very slow to close, even if they're readonly and nothing happens.

```
f = spacepy.pycdf.CDF('/home/share/data/EPIHi/masters/level2/psp_isois-epihi_l2-het-rates3600_00000000_v0.0.0.cdf')
f.close()
```

takes 20 seconds. This is running as a script from the command line so it isn't an ipython issue. This is a CDF with 2458 variables (!) Going to check it in C as well....

**Comment by jtniehof** [comment]
It's in the CDF library. This code:

```
#include <cdf.h>

void main(void) {
  CDFid infile;
  CDFopenCDF("/home/share/data/EPIHi/masters/level2/psp_isois-epihi_l2-het-rates3600_00000000_v0.0.0.cdf", &infile);
  CDFlib(SELECT_, CDF_READONLY_MODE_, READONLYon, NULL_);
  CDFcloseCDF(infile);
}
```
also takes 20 seconds, all in the close. Removing the selection of readonly mode and it's basically instant. This is really weird. If I set readonly on and then immediately set it off, the close is fast but setting READONLYoff is very slow.

We may want to not have pycdf automatically set readonly mode on open.

**Comment by jtniehof** [comment]
This is fast:
```
f = spacepy.pycdf.CDF('/home/share/data/EPIHi/masters/level2/psp_isois-epihi_l2-het-rates3600_00000000_v0.0.0.cdf', readonly=False)
f.close()
```

So I think the solution may be to document this rather than writing any new code.

**Comment by drsteve** [comment]
For now I agree with documenting this and moving on. We should probably pass a query about the (lack of) speed up to the CDF devs. Hopefully they can address it upstream.

**Comment by jtniehof** [comment]
Submitted upstream.
