### ISSUE TITLE
Use numpy distutils to build irbempy

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#112]
We're building the irbempy extension "by hand" with explicit calls to build irbem and then explicit f2py calls. @asreimer in #108 suggested using the numpy distutils for the build, with the extension class. Suggested example at https://github.com/aburrell/apexpy/blob/master/setup.py

I think I've looked at this in the past and it didn't play terribly well with some other stuff we were doing, but that was a long time ago and it's worth another look. We were also considering getting away from numpy distutils since it's been the cause of some problems (#45, 9da472340d23d0892ab0b828861372f8dcb3b908). It's also fixed some problems (3fcb9fdfe15834d7b27d90731f14bdd8dfccce65).

**Comment by jtniehof** [comment]
If we work on a new build system, there are probably other options to consider, e.g. https://mesonbuild.com/

**Comment by balarsen** [comment]
Doesn't #296 make this unneeded?

**Comment by jtniehof** [comment]
Even with #296 we still need IRBEM for L*, etc. (stuf that's in irbempy but not Coordinates).

**Comment by jtniehof** [comment]
Since I'm throwing general build system notes in here, [thread on projects that can't build into wheels](https://discuss.python.org/t/pep-517-and-projects-that-cant-install-via-wheels/791/6). We should be good with this given that, uh, we can build and install from wheels :) but in case something weird shows up there might be hints in there.

**Comment by jtniehof** [comment]
numpy distutils is no more, so this will not happen.
