### ISSUE TITLE
Make it easier to pass through Fortan compiler options for f2py

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#113]
If #112 proves untenable, we should try to support some ability to control Fortan and f2py options as attempted by @asreimer in #108. We had to do some hand-passthrough already (e.g. 252d6e567170ca4ecf6b51a2a0d12dacac4c2003) and it's a bit of a mess, so #112 is likely a better option.

**Comment by drsteve** [comment]
A probably relevant message I'm seeing on the IRBEM compilation at the moment:
```LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).```

Python: 3.7.3
Numpy: 1.16.3

**Comment by jtniehof** [comment]
Yep, that's the job of the back half of f2py_options. Looks like that was added in numpy 1.16.0 so once we decide that's the minimum, we can set that flag and rip out that back half. https://stackoverflow.com/questions/54201961/how-to-tell-f2py-module-to-look-in-current-directory-for-shared-object-dependenc

**Comment by jtniehof** [comment]
In the short term I suppose I should set that flag to 0 so we don't duplicate.

**Comment by jtniehof** [comment]
Note to self to double-check what the default fcompiler is for Windows; if it isn't gnu95 it should be since that's what actually works.
