### ISSUE TITLE
dmarray breaks on masking [Migrated from SF; Bugs #65 and #71]

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#12]
Combining two trackers from SourceForge:
[#65 dmarrays do not properly convert to masked arrays](https://sourceforge.net/p/spacepy/bugs/65/)

[#71 dmarray array behavior difference in np.median](https://sourceforge.net/p/spacepy/bugs/71/)

Basic summary of these two bug trackers is that dmarray is a subclass of numpy ndarray. A straightforward subclass of ndarray (e.g. following their RealisticInfoArray example) is that ufuncs like max, min, etc. behave inconsistently between numpy arrays and subclasses of arrays. The fix that was committed for this pushed the error further into hiding and manifested as a breakage on conversion to a MaskedArray. One major impact was that dmarrays needed to be converted to ndarrays before being passed to matplotlib's pcolormesh, but the issue was basically anywhere that masking was needed.

**Comment by drsteve** [comment]
Candidate fix for this issue is in the new_dmarray branch.

The fix subclasses MaskedArray, with some modifications to preserve existing dmarray behaviour.
So far (since TravisCI isn't hooked up yet) the new branch passes all of our tests, and tests of some downstream packages that rely heavily on dmarray also work. Several of the @spacepy/councilofelrond have also tested this branch on some dmarray-dependent analyses with no noted issues.

spacepy.poppy tests currently don't use dmarrays (need to check internals to see whether there's any use inside the module). Assigning myself this issue with task list:
- Test PoPPy with dmarray inputs.

Assuming spacepy.poppy test suite passes then I'll do a pull request. If anyone has any objections or additional testing requirements then please leave them here and we can address before merge.

**Comment by drsteve** [comment]
To update and clarify my previous comment:
- I have modified a few lines in the pycdf testing that test the output of xx.flat against yy.flat, where xx and yy may have different types. Because flat (ndarray/maskedarray) returns an iterator it depends on the subclass. Changing these to flatten() then compares objects and not iterators, so the tests compare the values and pass.
- One CDF test fails (in 2.7 and 3.6, seems to pass in 3.5??). The root cause appears to be in the "flat" method again. Specifically, the test for well-formed input data (staticmethod: check_well_formed) tests a slice from the flat iterator. Changing this to use flatten() passes all tests. My guess is that we should revisit check_well_formed as it's a bit klugey. I'm committing that change in the new_dmarray branch so that everything passes the tests.
- Changing the poppy suite (not committed) to use dmarrays instead of lists as input passes the tests, except where logical "any" or "all" methods need to be called. We can decide whether to update the tests later.


======================================================================
ERROR: testCreateCDFFromSpaceData (__main__.MakeCDF)
Make a CDF from a Spacedata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pycdf.py", line 675, in testCreateCDFFromSpaceData
    cdf.CDF.from_data(self.testfspec, sd)
  File "/home/smorley/.local/lib/python2.7/site-packages/spacepy/pycdf/__init__.py", line 1769, in from_data
    cdffile[k] = sd[k]
  File "/home/smorley/.local/lib/python2.7/site-packages/spacepy/pycdf/__init__.py", line 1599, in __setitem__
    self.new(name, data)
  File "/home/smorley/.local/lib/python2.7/site-packages/spacepy/pycdf/__init__.py", line 2092, in new
    (guess_dims, guess_types, guess_elements) = _Hyperslice.types(data)
  File "/home/smorley/.local/lib/python2.7/site-packages/spacepy/pycdf/__init__.py", line 3591, in types
    _Hyperslice.check_well_formed(d)
  File "/home/smorley/.local/lib/python2.7/site-packages/spacepy/pycdf/__init__.py", line 3525, in check_well_formed
    len(d.flat[0])
  File "/home/smorley/.local/lib/python2.7/site-packages/numpy/ma/core.py", line 2653, in __getitem__
    result = self.dataiter.__getitem__(indx).view(type(self.ma))
AttributeError: 'datetime.datetime' object has no attribute 'view'

**Comment by jtniehof** [comment]
Astropy Quantity is also ndarray subclass, http://docs.astropy.org/en/stable/_modules/astropy/units/quantity.html#Quantity

Maybe there are good ideas there (maybe it's affected by same problem.)

**Comment by jtniehof** [comment]
Sourceforge 71 works on current `main`:
```python

In [6]: numpy.median(spacepy.dmarray([]))
/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:3502: RuntimeWarning: Mean of empty slice.
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/usr/lib/python3/dist-packages/numpy/core/_methods.py:131: RuntimeWarning: invalid value encountered in divide
  ret = ret / rcount
Out[6]: nan
```

[MBE on SF](https://web.archive.org/web/20150327011818/https://sourceforge.net/p/spacepy/bugs/71/) was:
```python
In [1]: import numpy as np
In [2]: import spacepy.datamodel as dm
In [3]: np.median(np.array([]))
Out[3]: nan
In [4]: np.median(dm.dmarray([]))
ZeroDivisionError: float division by zero
```

**Comment by jtniehof** [comment]
SF65 is still broken on `main` but works on #766. Will update PR with test and magic words.
