### ISSUE TITLE
pycdf scalar indexing returning array scalar

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#123]
This shows how little I've been doing single scalar indexing...indexing a variable with a scalar returns a numpy array scalar rather than a single value:
```
In [7]: f['MET'][0]
Out[7]: array(291859185)
```

I'm not sure if this crept in somewhere or has been the case since the conversion to numpy, or even if it's necessarily undesirable, but definitely do need to check if it's a regression (a good one for people wanting to learn git bisect!) and, if so, fix and add a test.

If it's not a regression, question is if we're okay with this.

**Comment by jtniehof** [comment]
Okay, this does go all the way back to the initial numpy conversion. (Looking at 8458a1e). Do we think this is a problem? I can probably special-case it. It is a bit weird because it's not true with datetimes.

**Comment by spacecataz** [comment]
I've had instances where a numpy function returns an array scalar instead
of a true scalar.  In some cases, it does cause issues and I wind up doing
something like,
>>> x = np.some_func( y )[0]
to handle it... might be worth special casing.

-dw

**Comment by jtniehof** [comment]
I've got good news for you @spacecataz:  you can just do `x = np.some_func(y).item()` if you know it's going to be a scalar (That's what this fix does.)
