### ISSUE TITLE
Ability to access OMNI h5 file for jobs running in parallel

### ISSUE THREAD

**Issue by Rhyst223** [spacepy/spacepy#128]
Specifically, I am trying to calculate hourly Lstar values for a range of spatial locations over a range of years. Since this takes quite a while to run, I attempted to run as an array job on my institution's cluster with calculation for different years running in parallel.

However, when I execute the job I receive the following error:

### Error message/Traceback:

```
  GNU nano 2.3.1                              File: arrayJob_194706_1.out                                                                   

This array task index is 1
Run pysat.utils.set_data_dir to set the path to top-level directory that will/does contain science data.
Retrieving Qin_Denton file ...
^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Pro$

Now processing (this may take a minute) ...
Now saving...
Retrieving OMNI2 file ...
^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Progress ...0%^MDownload Pro$

Traceback (most recent call last):
  File "./Lstar.py", line 41, in <module>
    year = [Lcalc(glat[0],glon[0],h,exts) for h in time]
  File "./Lstar.py", line 25, in Lcalc
    Ls = [Lstar(t,y,extMag=j)['Lstar'][0][0] for j in exts]
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py", line 1681, in get_Lstar
    DALL = _get_Lstar(ticks, loci, alpha, extMag, options, omnivals)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py", line 1409, in _get_Lstar
    d = prep_irbem(ticks, loci, alpha, extMag, options, omnivals)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py", line 1737, in prep_irbem
    omnivals = omni.get_omni(ticks)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/omni.py", line 248, in get_omni
    with h5.File(fln) as hfile:
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/home/users/ph022752/.spacepy/data/omnidata.h5', errno = 17, error message = '$

                                                             [ Read 31 lines ]
^G Get Help            ^O WriteOut            ^R Read File           ^Y Prev Page           ^K Cut Text            ^C Cur Pos
^X Exit                ^J Justify             ^W Where Is            ^V Next Page           ^U UnCut Text          ^T To Spell
```
Upon some research I've found that it might be due to the h5 OMNI file only being allowed to be accessed by one process at a single time. Is this something that you were aware of? If so, is there any possible way to get around it?

### OS, Python version, and dependency version information:
Running in linux cluster, Python 2.7 environment

**Comment by jtniehof** [comment]
This looks like it might be trying to parallelize the download and saving of the OMNI data. Try running:
`spacepy.toolbox.update(all=True)`
before spawning the parallel processes. Otherwise if you can attach the script your running it might help.

**Comment by Rhyst223** [comment]
```
#!/usr/bin/env python
# coding: utf-8

# In[21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pysatMagVect._core import apex_location_info as apex
import sys


# In[3]:
from spacepy import coordinates as coord
from spacepy.time import Ticktock
from spacepy.irbempy import get_Lstar as Lstar
import spacepy.toolbox

spacepy.toolbox.update(QDomni=True)


# In[37]:
def Lcalc(glat,glon,time,exts,height=100):
    _,_,_,lat,lon,alt = apex([glat],[glon],[height],[time]) 
    t = Ticktock(time,'UTC')
    y = coord.Coords([alt[0]/6371,lat[0],lon[0]],'GEO','sph')
    Ls = [Lstar(t,y,extMag=j)['Lstar'][0][0] for j in exts]
    
    return Ls

# In[40]:
glat = [45.871,48.027,50.199,52.035,53.856,54.929,56.376,57.707,58.763,62.824]
glon = [264.917,263.635,263.960,264.537,265.340,264.713,265.300,265.794,265.920,267.890]
names = ['OSAK','THRF','PINA','LGRR','ISLL','OXFO','GILL','BACK','FCHU','RANK']

exts = ['0','MEAD','T87SHORT','T87LONG','T89','OPQUIET','OPDYN','T96','OSTA','T01STORM','T05']

#Pull in values from array job
y = int(sys.argv[1]) +1989

time = pd.date_range(start=str(y)+'01010000',end=str(y)+'12312359',freq='1H')

# In[43]:
year = [Lcalc(glat[g],glon[g],h,exts) for h in time]

# In[46]:
year_df = pd.DataFrame(year,columns=exts)

year_df.to_pickle('/home/users/ph022752/LSTAR/'+str(y)+'/'+ names[g]+str(y)+'.pkl.gz')





```
Here is the code, it runs in parallel by calling in array values with sys

**Comment by jtniehof** [comment]
If that whole thing is being parallelized by the cluster's job system spawning a bunch of processes, then definitely comment out/remove the update. Just run it once by itself and it'll get all the data downloaded into your .spacepy directory and will be available to all the processes (assuming the filesystem is replicated across the cluster.)

If then there's a failure on read, then there's a bug we should fix.

**Comment by Rhyst223** [comment]
There is still an error if the update is taken out, the same as the original:

```  GNU nano 2.3.1                              File: arrayJob_194911_2.out                                                                   

This array task index is 2
Traceback (most recent call last):
  File "./Lstar.py", line 43, in <module>
    year = [Lcalc(glat[0],glon[0],h,exts) for h in time]
  File "./Lstar.py", line 26, in Lcalc
    Ls = [Lstar(t,y,extMag=j)['Lstar'][0][0] for j in exts]
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py", line 1681, in get_Lstar
    DALL = _get_Lstar(ticks, loci, alpha, extMag, options, omnivals)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py", line 1409, in _get_Lstar
    d = prep_irbem(ticks, loci, alpha, extMag, options, omnivals)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/irbempy/irbempy.py", line 1737, in prep_irbem
    omnivals = omni.get_omni(ticks)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/spacepy/omni.py", line 248, in get_omni
    with h5.File(fln) as hfile:
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/users/ph022752/.conda/envs/rtenv27/lib/python2.7/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
IOError: Unable to create file (unable to open file: name = '/home/users/ph022752/.spacepy/data/omnidata.h5', errno = 17, error message = '$










                                                             [ Read 22 lines ]
^G Get Help            ^O WriteOut            ^R Read File           ^Y Prev Page           ^K Cut Text            ^C Cur Pos
^X Exit                ^J Justify             ^W Where Is            ^V Next Page           ^U UnCut Text          ^T To Spell
```

**Comment by drsteve** [comment]
I'm still a little fuzzy on just how this is being parallelized, but parallel IO isn't straightforward.

For starters, you'd need to ensure that your environment on your institutional cluster is using a parallel version of the HDF5 library (as opposed to the standard serial version). Similarly, h5py (which is what SpacePy uses to work with HDF5) needs to be specifically built for parallel IO. See: [http://docs.h5py.org/en/stable/mpi.html](http://docs.h5py.org/en/stable/mpi.html).

Even with that done, the read code would need to be rewritten to support parallel IO. It's not trivial to do that in a generic way and support a broad range of use cases - and anyway, Python isn't naturally parallel-friendly. In short, we don't support parallel IO. Given the reasons why, I'm inclined to say this *isn't* a bug.

I will point out, though, that `get_Lstar` is already parallelized for shared memory systems (i.e., it chunks the inputs and hands the chunks off to different processes before collecting the results). If you want to do your own parallelization you might want to call `_get_Lstar` instead, as that *isn't* parallel.


However, I have a few suggestions that may work:
1. Implement your parallel loop directly in the Python code, first loading the required input data, then passing that data to the function you wish to parallelize. `get_Lstar` \(or `_get_Lstar`\) will take an explicit dict/dict-like of inputs through the `omnivals` keyword argument. I'd use the `multiprocessing` module for this approach, probably with `Pool.map` \([docs](https://docs.python.org/3/library/multiprocessing.html#using-a-pool-of-workers)\)
2. Suggestion 1 may only work properly on a single node. I'm not sure that `multiprocessing` really supports distributed computing. There is the `mpi4py` library which will let you explicitly code all this up and pass info between nodes, but that's got a lot of learning curve.
3. It may be worth looking into `ray` \([docs](https://ray.readthedocs.io/en/latest/)\) as an option for parallelizing as in point 1. `ray` claims to support distributed computing fairly seamlessly, so it should have a much easier entry point than `mpi4py` while being flexible about single versus multiple nodes. Again, the parallelization would need to be done after loading the input data.
4. You could sidestep the parallel IO by launching different jobs each from different virtual environments on your cluster. That way each virtualenv has its own copy of the input data file.
5. I know this is the SpacePy github, but when I need to do lots of L* computations, or to run that kind of thing in parallel, I actually use LANLGeoMag \([github](https://github.com/drsteve/LANLGeoMag)\). That's a C library with good L* routines \(see, e.g., [Albert et al., 2018](https://doi.org/10.1029/2018JA025991)\) that is designed to be parallelizable. The big downsides are that it's a C library and you'd need to write a front-end application that was parallel. So if you're not comfortable with either of those then this is going to be a ludicrously high barrier to entry.


Feel free to drop me a line if you wanted a collaborator on this. Depending on your timeline and what you need to get done I can probably do these calculations fairly easily. My email is smorley. The domain is lanl.gov.

**Comment by jtniehof** [comment]
Opening read/write is the default and the OMNI module isn't specifying readonly. I'm guessing readonly would make this work. Coding up a test will be a bit odd but I do think it should be tested to be sure. I will try to carve out some time tomorrow to make that happen.

It seems parallel h5py should only be necessary if sharing the File objects across instances, not the physical file.

I also think the lgmpy L* should be pretty parallelizable with appropriate number of CTrans, etc. but that still needs some bashing (was planning to work on it today but ran out of time.)

**Comment by drsteve** [comment]
Read only *might* help in this case.
Parallel HDF would definitely be required for any kind of write from multiple processes. For read it would depend on how HDF handles opening files. 

If changing the HDF access in `get_omni` to be read only fixes this then I'm happy to do that. I would still recommend a single file read and then sending the required data, within Python, to the processes/workers that need it. I still don't think this is a bug, per se.

**Comment by jtniehof** [comment]
There's not much point to having it open RW and I confirmed that trying to open an hdf file multiple times RW in different processes does fail with the error given, whereas opening multiple times RO in different processes does work.
