### ISSUE TITLE
CDFWarning: DID_NOT_COMPRESS - better message, which var did not compress

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#135]
Is it possible for pycdf to report which variable did not compress?

### Minimal example to reproduce issue:
```
import spacepy.pycdf as pycdf
import numpy as np
a = np.asarray([1,2,3,4], dtype=np.int8)
cdf = pycdf.CDF('new1.cdf', '')
cdf.new('var1', compress=pycdf.const.GZIP_COMPRESSION,
                   compress_param=6, data=a)
cdf.close()
```

### Error message/Traceback:
```
/Users/balarsen/.local/lib/python3.7/site-packages/spacepy/pycdf/__init__.py:1944: CDFWarning: DID_NOT_COMPRESS: The CDF or variable values did not compress.
  *args, **kwargs)
```

**Comment by jtniehof** [comment]
Nothing to be done... that's exactly how it gets reported out from the
library, and it's usually on file close not the write.

It's not a problem as such. Usually that means the variable had very few
records there was no redundancy to eliminate.

**Comment by balarsen** [comment]
So I agree, but is possible to know which variable didn't compress? Sounds like not. If that's true go ahead and close.

**Comment by jtniehof** [comment]
No way to get that information. The close call returns a status code and
pycdf looks up the message for that code.... no means of querying for more
information.

**Comment by jtniehof** [comment]
It might be possible to reopen the closed cdf and query every single
variable for compression settings and actual compression ratio, but that
doesn't sound reasonable to do automatically. It might be worth writing a
little utility that would do it. So the question is how much your concern
is the warning message in general (hard to impossible to improve) vs.
providing a means to discover that information in a particular context
(possible).

**Comment by balarsen** [comment]
I agree way too much overhead, I will close this add a feature request for pycdf functionality to diagnose a cdf file.
