### ISSUE TITLE
Windows binary wheel support

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#156]
We want to support installing on Windows via pip from a binary wheel (so that users don't need a compiler.) Ultimately we'd like this for other operating systems, but this is just for Windows for now.

**Comment by drsteve** [comment]
Where does this sit with the merge of #159?

**Comment by jtniehof** [comment]
Probably very close to done, but I don't want to close it until I've run things through test pypi.

**Comment by jtniehof** [comment]
Going to call this done now...there may be issues to resolve, but it's at least reasonably functional and out there.
