### ISSUE TITLE
Comments and defaults in spacepy.rc

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#18]
Right now, if spacepy.rc doesn't exist, we populate it with the default values, but leave them commented out, with a further comment that they're the default:

    #foo = bar #default value in spacepy 0.0.0

Unfortunately configparser doesn't (by default) support comments at the end of line, only on a line by themselves. So if a user uncomments:

    foo = bar #default value in spacepy 0.0.0

then config option "foo" will have the value "bar #default value in spacepy 0.0.0". Which really makes a mess with, for instance, the URLs for downloading leapsecond data.

I'm thinking the best way to address this is:

    #Default from spacepy 0.0.0
    #foo = bar

although that does double the length of the rc. Note that we can't just put one "defaults from spacepy 0.0.0" at the top, since if spacepy.rc exists but a particular value doesn't, that line will be added.

**Comment by drsteve** [comment]
The suggested fix looks fine to me. I don't think I care about doubling the length of the rc, especially given how short it is. I've added some labels to this: I think this should be done for the next release, and I'm trying to tag easy stuff as easy to encourage PRs from outside the core team.

**Comment by jtniehof** [comment]
I'll leave this for a week for somebody new to tackle, feel free to ask for any pointers (you'd be looking at the end of _write_defaults in __init__). Then I'll go ahead and do my proposed solution when I have time.

(Althought I might instead of "Default from spacepy 0.0.0" make it "Default foo from spacepy 0.0.0".)
