### ISSUE TITLE
Toolbox.quaternionNormalize first/last error

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#184]
toolbox.quaternionNormalize gives the same result for `scalarPos='first'` and `scalarPos='last'` this should not be the case. 

### Minimal example to reproduce issue:
```
In [1]: import spacepy.toolbox as tb
This unreleased version of SpacePy is not supported by the SpacePy team.

In [2]: tb.quaternionNormalize([0.707, 0, 0.707, 0.2])
Out[2]: array([0.69337122, 0.        , 0.69337122, 0.19614462])

In [3]: tb.quaternionNormalize([0.707, 0, 0.707, 0.2], scalarPos='first')
Out[3]: array([0.69337122, 0.        , 0.69337122, 0.19614462])

In [4]: tb.quaternionNormalize([0.707, 0, 0.707, 0.2], scalarPos='last')
Out[4]: array([0.69337122, 0.        , 0.69337122, 0.19614462])
```

**Comment by drsteve** [comment]
See discussion in #268.
@balarsen - I'll close this in the near future unless I hear objections. The TL;DR version is that normalization basically divides each element by the norm and therefore you don't expect to see a difference depending on the scalar position.

**Comment by balarsen** [comment]
I am a bit confused here, why do we have `scalarPos` if it doesn't do anything?

**Comment by balarsen** [comment]
If this is a non-issue then close as invalid but it seemed funny to me.

**Comment by jtniehof** [comment]
As described in #268, it only makes a difference when constructing a scalar quaternion to avoid degeneracy:
```
In [3]: spacepy.toolbox.quaternionNormalize([1e-20, 1e-20, 0, 0], scalarPos='first')
   ...: 
Out[3]: array([ 1.,  0.,  0.,  0.])

In [4]: spacepy.toolbox.quaternionNormalize([1e-20, 1e-20, 0, 0], scalarPos='last')
Out[4]: array([ 0.,  0.,  0.,  1.])
```

**Comment by drsteve** [comment]
I agree that it's not necessarily obvious, but it is correct behaviour. As @jtniehof just said, the `scalarPos` argument is so that the identity quaternion is constructed correctly when the quaternions have a very small magnitude. Most of the time it makes no difference.

Now that we've aired this out I'll close.
