### ISSUE TITLE
pycdf: make v3 CDFs and TT2000 the default

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#198]
Right now pycdf sets backward compatible mode by default (the CDF library does _not_). At this point there should be nobody using version 2 of the library so the default should be not backward compatible.

I think this is going to require three releases: one to issue a warning that the default will change in the future (if set_backward hasn't been called yet one way or the other), one to similarly warn that the default has changed, and finally one to remove that warning.

**Comment by jtniehof** [comment]
"about to change" warning should be on next release.

**Comment by jtniehof** [comment]
I'm also thinking in terms of "hiding" the backward-compatible setting and just adding a kwarg to the CDF constructor if they want to make a backward-compatible one. There's not really much reason to go toggling it in the library. That's probably a secondary consideration though.

**Comment by jtniehof** [comment]
Also, thoughts on making this a DeprecationWarning vs. some other warning type? FutureWarning used to be the warning for "hey this is going to change" vs. being deprecated; now it's meant for end user vs. developer.

**Comment by balarsen** [comment]
I have no particular preference here, if I read the [CDF changelog](https://cdf.gsfc.nasa.gov/html/cdf_changesnote.html) correction v3 came out in 2005. Based on that I vote DeprecationWarning

**Comment by jtniehof** [comment]
Warning of upcoming change: 0.2.2
Change behavior and warn that it's changed: 0.3.0
Remove warning: 0.4.0

**Comment by jtniehof** [comment]
It's probably also worth changing the default time type to TT2000 as part of this transition....might as well get it all done at once.
