### ISSUE TITLE
updating or making the repository official 

### ISSUE THREAD

**Issue by dpshelio** [spacepy/spacepy#2]
Hello there, I've just met two of the spacepy developers, and they would like to get this repo either official, or update it - so the community is up to date if using this repository.  
If it's ok with you, you could add some of us to the team and we do the updating.

Thanks

**Comment by dpshelio** [comment]
@spacepy ??  anyone??

**Comment by graingert** [comment]
@dpshelio who need adding?

**Comment by dpshelio** [comment]
@graingert great! I met couple of weeks ago @drsteve - I don't know the github usernames of the other admins of the project, but he probably will be able to tell you.

**Comment by drsteve** [comment]
The relevant folks would be me (@drsteve), @balarsen and @jnlanl. 
We'd really appreciate being able to keep this up-to-date.

**Comment by jtniehof** [comment]
My non-LANL account would probably be appropriate at this point (@jtniehof rather than, or in addition to, @jnlanl)

**Comment by graingert** [comment]
invited, check your emails etc

**Comment by dpshelio** [comment]
Thanks @graingert
