### ISSUE TITLE
Error in conversion between GEO/SPH coordinates and RLL coordinates

### ISSUE THREAD

**Issue by aaronhendry** [spacepy/spacepy#213]
There is an error in the conversion from spherical geocentric coordinates and RLL coordinates. To see this in action, consider the following simple example:

```python
from spacepy.coordinates import Coords
from spacepy.time import Ticktock

c = Coords([[1,45,60]],'GEO','sph',ticks=Ticktock.now())
d = c.convert('RLL','sph').convert('GEO','sph')

print(c.data)
print(d.data)
```

#### Expected output
This should print the following:
```python
[[ 1 45 60]] # c
[[ 1 45 60]] # d
```
While the conversion to geodetic coordinates is not strictly exact, we should expect that the conversion to and from RLL coordinates should return roughly the same initial vector. This is not the case

#### Actual output
```python
[[ 1 45 60]] # c
[[75.00666637 45.18974511 60.        ]] # d
```
Clearly there is a serious error in this conversion process, as the final coordinate `d` is starkly different from the input coordinate. I believe this is due to an error in the IRBEM library -- I have traced it to the following code from `CoordTrans.f`:

https://github.com/spacepy/spacepy/blob/8c5b83c6a7fd6d87dc034255dba5cf02e4439f29/spacepy/irbempy/irbem-lib-2019-04-04-rev616/source/CoordTrans.f#L1846-L1856

Specifically, it seems that the RLL radius is being calculated from the norm of the *spherical* geocentric coordinate rather than the *cartesian* geocentric coordinate. I believe that line 1853 should be replaced by something like:

```fortran
            xOUT(1)=xIN(1)
```
i.e., setting it to the geocentric radius of the input point. This actually raises a separate issue -- RLL is stated as being a geodetic coordinate system, yet it uses the geocentric radius -- is this correct?

This was tested in Spacepy 0.2.0 in Python 3.5.2, but as this is an issue with the underlying IRBEM library, it is largely spacepy agnostic.

**Comment by drsteve** [comment]
I'm happy to also take a look (I'm unavailable until next week) and feed back to @AntoineBrunet too. I believe there are also some unresolved inconsistencies in the inertial coordinate systems that affect a couple of conversions. Those will not have the same impact as this one though.

As far as the use of the radius goes, my first thought is that this is fine, as geodetic coordinates are defined as altitude, geodetic latitude and geodetic longitude. The correct altitude will require use of a geoid, but the radius is the radius, regardless of the shape of the Earth.

I've never seen a clear use-case for RLL though. Geodetic, yes. Spherical geographic, yes. RLL, no. That aside, I think this really highlights the need for testing in the IRBEM library.

It also highlights the need to look again at using the well-tested coordinate transforms from LANLGeoMag (either wrapped or ported) as the backbone (or at least as an option) for Spacepy's coordinate transformations.

**Comment by aaronhendry** [comment]
Thanks, I will create a ticket on the IRBEM sourceforge page. 

I was unsure myself about the geodetic vs. geocentric radius for RLL. The main reason I started to wonder about it was because it means that the RLL and GDZ vectors are not parallel (because the GDZ vector points parallel to the surface, rather than towards the centre). As you say, I suspect this is not an issue as such.

I don't typically use RLL myself, however I noted that in the IRBEM documentation that the RLL coordinate system is preferred over SPH. That's what started me down a rabbit whole of comparing them and finding the above bug.

**Comment by jtniehof** [comment]
Upstream bug [here](https://sourceforge.net/p/irbem/bugs/8/)

**Comment by drsteve** [comment]
I took the liberty of fixing this upstream (r619). I've also committed r620 upstream to add update IGRF/DGRF coefficients.

That would make now a really great time to update the IRBEM version in SpacePy...
