### ISSUE TITLE
spacepy plot style deprecated in matplotlib 2.2.3

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#22]
```
from spacepy import plot as spp

Bad key "axes.color_cycle" on line 17 in
/Users/balarsen/Library/Python/3.6/lib/python/site-packages/spacepy/data/spacepy.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
```

So the rc has changed with matplotlib.

**Comment by drsteve** [comment]
Fixing this requires changing the color cycler in the mplstyle files to a properties cycler. This is an easy fix but seems to imply a bump in the required version of matplotlib. I.e., supporting the newest matplotlib mean dropping support for versions before 1.5 (as best I can tell). Se issue #8 for a fuller discussion.

I note that our tests are showing a number of other matplotlib deprecation warnings. If we're okay with changing the minimum supported versions of numpy, scipy, matplotlib (as per #8) then I have a candidate branch that will resolve this issue (mpl_updates at drsteve/spacepy) and I'll submit a PR when I've had some more feedback on the versions.

**Comment by jtniehof** [comment]
You know I don't like having the plot styles, but given we have them, I agree with 1.5 as a minimum and would approve a PR.

**Comment by jtniehof** [comment]
Steve, is this related to why Travis is failing on seapy? Or should I comment on the travis issue? I swear I didn't touch seapy in my commits.

**Comment by drsteve** [comment]
I think so. It looks like the tests are now pulling a newer version of MPL from pip. I'll go ahead and submit my PR with all my matplotlib fixes. If you can inspect and merge that then I'll rerun the tests for your PRs and merge them.

**Comment by jtniehof** [comment]
I can rebase them (I think) once your PR is merged. We'll see how that goes.
