### ISSUE TITLE
pycdf.istp.VarBundle needs better way to show involved variables, repr

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#227]
As discussed in #222, VarBundle doesn't have a very good repr, nor a good way to see what variables are involved. The repr should at least show the main variable (and maybe the related ones) and there should be some way to find the related variables, with the caveat that not all related variables are always included in the output.

**Comment by jtniehof** [comment]
This should be designed in such a way that there's some idea of association between variables and dimensions, so if you're poking at a variable interactively you can guess which dimension you might want to be doing the slicing on.

**Comment by jtniehof** [comment]
I think I've got an idea for the baseline here. Add a method `inspect` which returns a `dict` describing lots of things about the bundle:

Key `operations` is a list describing the operations to perform on the bundle. Each element is a tuple: first element is a string with the name of the operation (i.e. method of `VarBundle`) and remaining elements are the arguments. So:
```
vb.slice(1, 2, 15).sum(1).mean(2).inspect['operations']
#[('slice', 1, 2, 15), ('sum', 1), ('mean', 2)]
```

Key `vars` is a list-of-lists-of-tuples. From the top level, each element is a list corresponding to a dimension of the master var: first the master var itself, then the uncertainties and labels associated with each dimension. Each element of these sublists is then a tuple of variable name and shape on the output (itself a tuple). If a variable isn't included in the output (sliced away), its shape will be `None`. So:
```
[
[('main', (5, 6)), ('main_DELTA', (5, 6))],
[('Epoch', (5,)), ('Epoch_DELTA', ())],
[('dep1var', (6,)), ('dep1var_DELTA', (6,)), ('dep1label', (6,))],
[('dep2var', None)]
]
```
would mean:
Variable `main` is the main variable (the one passed in to the constructor). After slicing, it'll be (5, 6) on the output, as will its delta. `Epoch` is the DEPEND_0 and has a constant DELTA. `dep1var` is the DEPEND_1, it has its own DELTA, and LABL_PTR_1 is `dep1label`. There's also a `dep2var` which is the DEPEND_2, but it was sliced entirely away.

I think there should be a verbose explanation function (maybe `explain` or `verbose`?) that would return a string with all this nicely formatted:
```
slice(1, 2, 15).sum(1).mean(2)
main(5,6) main_DELTA(5,6)
Epoch(5) Epoch_DELTA()
dep1var(6) dep1var_DELTA(6) dep1label(6)
dep2var
```

And then `__str__` just returns all the variable names, bracketing out the exclusions:
`main main_DELTA Epoch Epoch_DELTA dep1var dep1var_DELTA dep1label (dep2var)`

And `__repr__` is the usual str-plus-brackets:
`<VarBundle: main main_DELTA Epoch Epoch_DELTA dep1var dep1var_DELTA dep1label (dep2var)>`

@balarsen , thoughts, particularly on naming? I think the `vars` key is maybe a little overengineered; it's a lot of information, but it all does sort of hang together.

**Comment by balarsen** [comment]
I can see utility in each of them. 

`vars` is really useful for debugging and understanding what you are doing. But as you say may be overkill. 

`__str__ `and `__repr__` as you have them defined above may be enough info. Why is `dep2var `in `()`?

I don't really have a strong thought on what is the best solution, the use case I envisioned was a call with a name like `vars ` but just a list with the contents of `__str__ ` as you have it. 

Another way to think on this is that the `vars `  in your example is the representation of some kind of `CDFBundle` class that you use to do the bundling. But sounds like a lot of work for not a lot of payoff.

**Comment by jtniehof** [comment]
The `VarBundle` is basically the `CDFBundle` class as you described.

I put dep2var in parens since it's not included in the output. I was also thinking putting a * next to it?

`__str__` and `__repr__` would basically pull from the more comprehensive `inspect` (as would `explain` --or maybe `describe`?)

**Comment by jtniehof** [comment]
Hmmm, `operations` as I described it won't work, because `slice` takes a kwarg, so can't represent all its args as a tuple. I suppose one option would be to go full-on Python and have args + kwargs:
```
vb.slice(1, 2, 15).sum(1).mean(2).inspect['operations']
#[('slice', (1, 2, 15), {}), ('sum', (1,), {}), ('mean', (2,), {})]
vb.slice(1, 2, single=True).mean(2).inspect['operations']
#[('slice', (1, 2, 15), {'single': True}), ('mean', (2,), {})]
```

Or just specify a kwarg dict as the last element of the tuple if there are any:
```
vb.slice(1, 2, 15).sum(1).mean(2).inspect['operations']
#[('slice', 1, 2, 15), ('sum', 1), ('mean', 2)]
vb.slice(1, 2, single=True).mean(2).inspect['operations']
#[('slice', 1, 2, 15, {'single': True}), ('mean', 2)]
```

A lot of the difficulties are coming from trying to distinguish between "Slice from n to end" and "Just slice out n itself."

I do think "operations" being a bit clunky is okay, so maybe it should just be a list of tuples of (function name, args, kwargs) (i.e. first option in this comment)
