### ISSUE TITLE
fortran build fails on arm

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#23]
python setup.py build --fcompiler=gnu95 yields error message "gfortran: error: unrecognized command line option ‘-m32’" on raspbian. uname: Linux midori 4.14.69-v7+ #1141 SMP Mon Sep 10 15:26:29 BST 2018 armv7l GNU/Linux. This is the default compiler (and gnu doesn't work.)

**Comment by jtniehof** [comment]
@drsteve: Since we didn't have explicit arm support before, I'm thinking of just starting a branch and knocking things down in a series and submitting a single PR when all tests pass, rather than a PR for each fix. Sound reasonable? I can also then make the branch off the main repo rather than my fork so it's a little more visible.

**Comment by drsteve** [comment]
Sure. I'll make a project board for explicit ARM support and drag any ARM-reltaed issues to it so it's obvious that it's being worked.
