### ISSUE TITLE
OMNI data is only available through January 2017

### ISSUE THREAD

**Issue by ljlamarche** [spacepy/spacepy#233]
Updating the OMNI database with [spacepy.toolbox.update()](https://pythonhosted.org/SpacePy/autosummary/spacepy.toolbox.update.html#spacepy.toolbox.update) only updates the database up to January 31, 2017.  This is probably because the source used for OMNI data ([ViRBO](http://virbo.org/)) is no longer maintained.  NASA's [Space Physics Data Facility](https://spdf.gsfc.nasa.gov/) looks like it is the appropriate place to get this data now.

The spacepy [omni documentation](https://pythonhosted.org/SpacePy/omni.html) states that
>"The omni module primarily manages the hourly OMNI2 and Qin-Denton data, which are sourced from the Virtual Radiation Belt Observatory (ViRBO), who maintain these data sources."

However, the [ViRBO](http://virbo.org/) page states 
>"The ViRBO project was discontinued in 2014 and these pages are no longer being updated."

The contents of `~/.spacepy/spacepy.rc` confirm that both the omni2 and the qindenton data is being sourced from the ViRBO site.
```
[spacepy]
  
#apply_plot_styles: True #default in SpacePy 0.1.6
#enable_deprecation_warning: True #default in SpacePy 0.1.6
#leapsec_url: ftp://maia.usno.navy.mil/ser7/tai-utc.dat #default in SpacePy 0.1.6
#ncpus: 8 #default in SpacePy 0.1.6
#omni2_url: http://virbo.org/ftp/OMNI/OMNI2/merged/latest/OMNI_OMNI2-latest.cdf.zip #default in SpacePy 0.1.6
#psddata_url: http://spacepy.lanl.gov/repository/psd_dat.sqlite #default in SpacePy 0.1.6
#qindenton_url: http://virbo.org/ftp/QinDenton/hour/merged/latest/WGhour-latest.d.zip #default in SpacePy 0.1.6
#support_notice: True #default in SpacePy 0.1.6
```
After running [spacepy.toolbox.update()](https://pythonhosted.org/SpacePy/autosummary/spacepy.toolbox.update.html#spacepy.toolbox.update), both `~/.spacepy/data/omni2data.h5` and `~/.spacepy/data/omnidata.h5` are modified, however, the last time stamp in `omnidata.h5` is `2017-01-31T23:00:00` and the last time stamp in `omni2data.h5` is `2012-12-31T23:30:00`. 

![omnidataSS](https://user-images.githubusercontent.com/23563101/67340780-0f1fb300-f4e3-11e9-9461-f40c17061853.png)
![omni2dataSS](https://user-images.githubusercontent.com/23563101/67340772-08913b80-f4e3-11e9-9835-ec38e1cf385c.png)

Both low and high resolution OMNI data can be found from [SPDF](https://spdf.gsfc.nasa.gov/pub/data/omni/).

### Minimal example to reproduce issue:

```
import spacepy.toolbox as tb
tb.update(omni=True)

import spacepy.omni as om
print('OMNI RANGE:', om.omnirange())

# This produces an error
import spacepy.time as spt
import datetime as dt

st = dt.datetime(2017,5,27)
en = dt.datetime(2017,5,28)
ticks = spt.tickrange(st, en, dt.timedelta(hours=1), 'UTC')
data = om.get_omni(ticks)
```

### Error message/Traceback:

This is the full output from the code above.  Even after updating, the latest date where data is available is still January 1, 2017, which causes and error to be raised when data from May 2017 is requested.

```
Retrieving Qin_Denton file ...
Download Progress ...100%

Now processing (this may take a minute) ...
Now saving... 
OMNI RANGE: (datetime.datetime(1963, 11, 27, 14, 0), datetime.datetime(2017, 1, 31, 23, 0))
Traceback (most recent call last):
  File "update_spacepy.py", line 14, in <module>
    data = om.get_omni(ticks)
  File "/anaconda2/envs/python3.6/lib/python3.6/site-packages/spacepy/omni.py", line 254, in get_omni
    raise ValueError('Requested dates are outside data range')
ValueError: Requested dates are outside data range
```

### OS, Python version, and dependency version information:

**OS:** Darwin-17.7.0-x86_64-i386-64bit
**Python:** 3.6.8
numpy=1.16.2
scipy=1.2.1
matplotlib=3.0.2

### Version of SpacePy

spacepy=0.2.1

**Comment by drsteve** [comment]
Thanks for the report.
We will need to update our data sources, and this will also need code changes.

The OMNI2 data is indeed best sourced from SPDF, and we'll need to either pull multiple files (then either manage or combine) or we'll need to switch to fetching and parsing the combined ASCII file.

The "omni" originally sourced from ViRBO (source labeled as `qindenton_url` in the `spacepy.rc` is not available from SPDF, as it's a derived data product that fills gaps and calculates the various input parameters required for the Tsyganenko magnetic field models (weighted averages, etc.). We do have access to the post-processing code, and will need to look into how best to process, format, and distribute that data. ViRBO isn't "active" but they do maintain their old content, so we may be able to push data updates without requiring manual input from ViRBO. (The 2017 update was generated by me and uploaded manually by the ViRBO owner ... it's not a fix, but I will look into generating and pushing another update)

In short, thanks - this has been a "forgotten" problem on our end, and we really need to do something to fix it. Having an open issue should help this stay near the top of the priority list. So, my thought for what we (the _SpacePy_ team) need to work on:
- Updates to work with the OMNI2 data are a good first step and will be the easier to fix.
- Updates to the Qin-Denton data will need some extra thought and logistical handling.
- We need to improve the documentation for the `dbase` kwarg in `get_omni`. If you look at the _Advanced Features_ section of the docs at https://spacepy.github.io/omni.html it describes how to use an archive of JSON-headed ASCII files as an alternative source. Qin-Denton files at hourly, 5-min and 1-min resolution have been provided by the Van Allen Probes ECT team at Los Alamos National Lab and the New Mexico Consortium that meet this definition and these can be found at: https://rbsp-ect.newmexicoconsortium.org/data_pub/QinDenton/ Until we've resolved the problem as described then this is a good workaround.

**Comment by jtniehof** [comment]
@drsteve , do we want to break this into several issues? OMNI2 from SPDF, Q-D from ECT, long-term Q-D? You've broken it down pretty well and I think we can work them independently.

Long-term for the Q-D files, we can look at hosting them on the SpacePy site on github, or maybe we should arrange with CCMC. Van Allen Probes is entering Phase F and so I don't know how long we can rely on that.

**Comment by jtniehof** [comment]
Note that most of the USNO services are down as well, so leapsecond updates don't work right now. NIST might have an alternative but all I can find is a fancy-formatted page not a simple ASCII list.

**Comment by jtniehof** [comment]
(Working on OMNI2 from SPDF just so nobody else jumps in....)

**Comment by drsteve** [comment]
@jtniehof Yes, breaking into several issues is good.
A few suggestions (that can be filed for future updates):
- CDAWeb has a RESTful API (see https://cdaweb.gsfc.nasa.gov/WebServices/REST/) that might be useful to use so we can more easily extend to other data sets.
- I have found some ASCII lists for leap seconds in case we wanted to add alternative URLs? E.g., https://data.iana.org/time-zones/data/leapseconds

**Comment by jtniehof** [comment]
With the merge of #241, `master` now grabs from SPDF for OMNI2. This will be in the next release. I'll start in on work for the QD files but it might not make next release.

**Comment by jtniehof** [comment]
USNO is now saying they won't be back until April 30 (!) They seem to be the official reference per IERS; the other official reference is the Paris IERS observatory, which is in a different format. iana.org is in yet a THIRD format. I can't believe there isn't a well-mirrored definitive location in consistent format...

So if we allow multiple URLs for leap seconds, we'll have to guess across multiple formats, too.

**Comment by jtniehof** [comment]
NMC RBSP-ECT site is down (@balarsen ?) LANL is up but only through 2017.

**Comment by balarsen** [comment]
Thanks. I’ll poke the site.
