### ISSUE TITLE
plot utils docs not being built

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#242]
The `plot.utils` docs aren't being generated, probably something weird with the autosummary for submodules.

**Comment by jtniehof** [comment]
I think adding a Submodules section, as at the bottom of pycdf.rst, to plot.rst, should do the trick.

**Comment by asher-m** [comment]
Yep, that seems to have done the trick.  I'll make a PR in a moment.

**Comment by jtniehof** [comment]
Probably better as a separate PR that just includes this (relative to master, please.)

**Comment by asher-m** [comment]
Just created the pull request.  As I mention there this _does_ fix the problem that plot.utils wasn't being linked to the docs for plot, but I've realized now that spectrogram (the submodule) and spectrogram.spectrogram (the class in the spectrogram submodule) aren't being linked either.  It'd make sense to fix both of these now.
