### ISSUE TITLE
plot.utils.EventClicker with non-tz datetimes

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#243]
`matplotlib.dates.num2date` returns dates with a tzinfo object (at least now it does.) This is causing failures "TypeError: can't compare offset-naive and offset-aware datetimes" in _relim in the bisects for a plot made from tz-naive datetimes.

```
ticks = spacepy.time.tickrange('2001-01-01', '2010-12-31', deltadays=datetime.timedelta(hours=1))
data = spacepy.omni.get_omni(ticks)
plt.plot(data['UTC'], data['Pdyn'])
clicker = spacepy.plot.utils.EventClicker(n_phases=1)
clicker.analyze()
```

**Comment by asher-m** [comment]
Hi Jon, as discussed, I can handle this.  (So you should be able to assign me this bug now.)
