### ISSUE TITLE
BAD_ENTRY_NUM when reading CDF file

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#25]
New bug report filed on the old Sourceforge tracker.
[https://sourceforge.net/p/spacepy/bugs/102/](https://sourceforge.net/p/spacepy/bugs/102/)

Submitted text (by Baptiste Cecconi) follows:
I'm running a pipeline that produces a series of CDF files, and then read them again one after the other to extract global attributes and write archive labels for each file. Every file is open and closed one after the other in a for loop. Once in a while, I get the following error:

File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/init.py", line 517, in check_status
raise CDFError(status)
spacepy.pycdf.CDFError: BAD_ENTRY_NUM: Illegal attribute entry number specified.

Usually I just re-run the processing again and it works, but this not very satisfactory. I see that this bug seems to be already detected and solved:

Commit [d043ae]
pycdf: fix occasional BAD_ENTRY_NUM when looking up zEntry type

Any idea of why this re-appeared ?

**Comment by drsteve** [comment]
Thanks Baptiste,
My first question would be whether you installed SpacePy from PyPI, or one of the release tarballs, or whether you built from the repo. The commit that should have fixed this was included in our last release, but it'd be really helpful to know the version of your SpacePy.

My second question would be to ask which version of the CDF library you're using. It's possible that they changed something internal that affects how we access the entry numbers.

**Comment by jtniehof** [comment]
A fuller traceback would be useful, too. If you're able to share the code that's causing the issue, best...there's nothing like being able to reproduce. It's possible that this is a similar bug rearing its head in a different place.

**Comment by jtniehof** [comment]
Just looking at the code, I'm seeing a couple of places something similar could be triggered. Sadly I think it could happen on either read or write. I'd still prefer to be able to reproduce the problem before pushing a patch just so I can have a clue that it actually worked. Once we know what version this is happening on, I can probably shoot over a replacement pycdf file that would potentially fix just this.

**Comment by BaptisteCecconi** [comment]
Hi Steve and Jon, thanks for your initial feedback. 

### Versions
* I use Python 3.5. 
*SpacePy is installed with pip:
```
[py35] [macbookbc:~/PycharmProjects/CassiniKronosPlasmaParamsArchive] baptiste% pip3 list | grep spacepy
spacepy                  0.1.6
``` 
* CDF-C library version is 3.6-4.

### Code
The code is available on my institute gitlab repo: https://gitlab.obspm.fr/cecconi/cassini-rpws-hfr-qtn-archive-pds4
However, as mentioned in the initial post, this bug is intermittent. I hit it sometimes, and usually if I wait for some minutes before I run it again, it just disappears.

**Comment by BaptisteCecconi** [comment]
well, I haven’t fully tested the gitlab release... but it should work.

**Comment by BaptisteCecconi** [comment]
Here is the full error stack:
```
[py35] [macbookbc:~/PycharmProjects/CassiniKronosPlasmaParamsArchive] baptiste% python3 qtn.py --labels
<class 'spacepy.pycdf.CDF'> co_rpws_hfr_qtn_200406301642_200407010951_v10.cdf
Traceback (most recent call last):
  File "qtn.py", line 791, in <module>
    file_process_log.write(make_pds4_pdf_file_label(item))
  File "qtn.py", line 601, in make_pds4_pdf_file_label
    return make_pds4_file_label(file_path, file_type='pdf')
  File "qtn.py", line 644, in make_pds4_file_label
    cur_file = cur_dir_file / str(cur_cdf.attrs['file_plot_name'])
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 3930, in __str__
    return '\n'.join([str(item) for item in self])
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 3930, in <listcomp>
    return '\n'.join([str(item) for item in self])
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 3879, in __iter__
    value = yield(self._get_entry(current))
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 4151, in _get_entry
    length = self._entry_len(number)
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 3978, in _entry_len
    const.GET_, self.ENTRY_NUMELEMS_, ctypes.byref(count))
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 3963, in _call
    *args, **kwargs)
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 1720, in _call
    *args, **kwargs)
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 565, in call
    *(args + (const.NULL_, ))
  File "/Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/spacepy/pycdf/__init__.py", line 517, in check_status
    raise CDFError(status)
spacepy.pycdf.CDFError: BAD_ENTRY_NUM: Illegal attribute entry number specified.
```

**Comment by jtniehof** [comment]
I can't reproduce this but submitted a PR that will likely address the problem. If you'd like to just test the patch, cd to ` /Users/baptiste/Development/pyvenv/py35/lib/python3.5/site-packages/` and run `patch -p1 < bad_entry_num.patch`  (providing the full path to wherever you put the patch file.)

Github doesn't let me attach patch files. So we're going to call it a .txt and hope it doesn't reformat it or anything.
[bad_entry_num.patch.txt](https://github.com/spacepy/spacepy/files/2406585/bad_entry_num.patch.txt)

**Comment by BaptisteCecconi** [comment]
I've run the patch as you proposed, and ran my scripts a few times in a row. I should have hit the bug, this way. And it seems to be solved ! 👍 
I'll post here if the bug reappears.
Thanks !
