### ISSUE TITLE
pybats: Kp histogram-style plots produce poor/incorrect results.

### ISSUE THREAD

**Issue by spacecataz** [spacepy/spacepy#252]
When using spacepy.pybats.kyoto.KyotoKp object's add_histplot function, instead of producing a continuous, single-valued, step-function-like plot (as is expected for the 3-hour Kp index), the line crosses over itself, duplicating previous times in an obviously incorrect fashion.

I will push solution shortly.

### Minimal example to reproduce issue:

```
from spacepy.pybats import kyoto
a = kyoto.fetch('kp', (2003, 10), (2003, 10))
a.add_histplot()
```

No traceback, just discontinuous/scattered results.

### OS, Python version, and dependency version information:
Issue is platform independent.

**Comment by drsteve** [comment]
Suggestion... the solution could call `spacepy.plot.levelPlot`
