### ISSUE TITLE
Spacepy working with intersphinx

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#257]
It would be awesome if spacepy worked with [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) from other packages. 

I have no idea how to accomplish this.

**Comment by jtniehof** [comment]
It does. We have objects.inv at https://spacepy.github.io/objects.inv so people can link to us (I use it on the ISOIS data processing code documentation) and we cross-link to numpy, scipy, matplotlib. Anything you were thinking that needs to happen?

**Comment by balarsen** [comment]
Ahh awesome. Do we have a good example of how to do this? I seem to be having a bad time with everything that is not Numpy or standard lib. 

:spacepy: ??

**Comment by jtniehof** [comment]
You have to add SpacePy to your [intersphinx_mapping](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#configuration) in `conf.py`:
```
intersphinx_mapping = {
    'spacepy': ('https://spacepy.github.io/', None),
...
}
```

Then just [cross-reference](http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#xref-syntax) like normal in the docs...it's still in the [Python domain](http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html), which is the default.

   ```
 """Add V_PARENT information for a variable

    :param var: the variable for which parent information will be
                added
    :type var: :class:`~spacepy.pycdf.Var`
    :param infile: CDF from which the variable was derived
    :type infile: :class:`~spacepy.pycdf.CDF`
    :param str oldname: Name of the variable in the old CDF from which
                         this variable was derived; default to same as
                         this variable.
    """
```

An example using `numpydoc` format is in `toolbox.feq` or `toolbox.binHisto` or `toolbox.bootHisto`.

If numpy and stdlib work but nothing else does, chances are you need to add them to the `intersphinx_mapping`, as described at the top of the page you linked....

**Comment by balarsen** [comment]
I have the others in the intersphinx mapping. All I see different is the ~. Anyway I’ll close this as already there.
