### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#26]
(Before anybody panics: the title of this issue is to indicate we'll close it when Python 2 support is removed, not that this is an immediate goal!)

Python 2.7 will be unsupported sometime in 2020. All our dependencies have pledged to EOL Python 2 support no later than that ( https://python3statement.org/ ). I suggest a gradual phase-out:

1. No prebuilt Python 2.7 packages: We should deliver one for 0.1.7. But potentially not as soon as the next release (presumably 0.1.8). June 2019, perhaps?
2. Allow new features/functions that don't support Python 2.7 as long as they don't break existing functionality. Beginning of 2020?
3. No workarounds for versions of dependencies that don't support Python 3; I'd lump the date in with 2.
4. No fixes for bugs that cannot be reproduced on Python 3. I would take this as the latter of June 2020 and when numpy, scipy, matplotlib have all released versions that do not support Python 2, with a caveat of no later than fall AGU of 2020.
5. Actively remove existing Python 2 code from the codebase: January 1, 2021.

This would mean a committment to full support of Python 2.7 through June 2019 (or whatever date is chosen for 1), followed by a phaseout of 12-18 months, while still falling within the 2020 pledge.

**Comment by jtniehof** [comment]
Actually I see CPython 2.7 support officially dies 1 Jan 2020, so I think this should happen sooner.

**Comment by balarsen** [comment]
Here is numpy's plan:
https://github.com/numpy/numpy/blob/master/doc/neps/nep-0014-dropping-python2.7-proposal.rst#plan-for-dropping-python-27-support


Our current plan is as follows.

Until December 31, 2018, all NumPy releases will fully support both Python2 and Python3.

Starting on January 1, 2019, any new feature releases will support only Python3.

**Comment by jtniehof** [comment]
Thanks Brian. I think the idea of trying to make sure "pip install spacepy" on Python 2 will always get the latest python 2 supporting one makes sense.

Reasonably compatible with that, I think my #1, #2, #3 could be lumped together as "after the first release after June 2019" (note #3 should be "no workarounds for dependencies that don't support Python 2"); leave #4 as June 2020 and #5 as January 2021. That still puts us as "no" to Python 2 in 2020, while being about 6mo behind numpy.

I do want to draw a distinction between "no further development on Python 2" and "ripping out Python 2" because I think that's a reasonable transition, as much as I'm itching to take a chainsaw to Python 2 code.

**Comment by balarsen** [comment]
@jtniehof @drsteve where do stand on this one as we enter 2022? Some thoughts/questions for the group.

1. As we update files should we be stripping all the stuff for python 2? 
2. Should we be specifically be doing py2 removal work? (like if we are procrastinating real work)
3. Should we be doing the typing stuff that py3 allows?

I don't feel strongly but as there is a lot of cleaning going things like this can go. 

https://github.com/spacepy/spacepy/blob/4fd13dd84f903c5a130897463b2ed308861ced6a/spacepy/toolbox/__init__.py#L76-L80

**Comment by jtniehof** [comment]
See https://spacepy.github.io/py2k_eol.html . The short is please don't start stripping Python 2 support or adding in type hints. I intend to iterate pretty quickly through 0.3 and 0.4 to get to 0.5.

I've promised @drsteve #296 for 0.3, and really just need to get some time to review that. If you can take another look and provide your input that might help speed it along.

Once we reach 0.5, we can talk about what version of Python 3 we want to require. Moving to 3.5 including the type hints makes sense to me, but we really should finish this transition first.

0.5 might actually be 1.0, or if we feel we want to do some work once the main migration is done, maybe 1.0 will follow 0.5. But I think we're at that point.

**Comment by jtniehof** [comment]
And I know I'm way behind on the dates on that time line.

**Comment by balarsen** [comment]
Thanks!!!  This is exactly why I asked. I have been (more than) a bit absent and don't want to f-up the plan.
