### ISSUE TITLE
trace2d modifies the field data

### ISSUE THREAD

**Issue by henry2004y** [spacepy/spacepy#276]
Hi,

I looked into the c source code [ctrace2d.c](https://github.com/spacepy/spacepy/blob/master/spacepy/libspacepy/ctrace2d.c), and probably found a bug. The returned field data is normalized after the make_unit function call, and it never gets it original value back. This can be easily checked with the standalone C code by printing out the ux, uy values in the test function.

A quick fix is to allocate new arrays for the normalized field data.

**Comment by spacecataz** [comment]
Greetings.

This is not an issue as the normalized field values are not passed back to the calling python functions.  As the underlying C code does not maintain the data between calls, this is not an issue.  

Note that the C code is not meant to be a standalone source that has data persistence between calls.  As such, this is not a bug and the code is working as intended.

You can test this by using the C module as intended, e.g., through tracing a flow vector field through BATS-R-US results and seeing that the data in the python object does not change.

**Comment by jtniehof** [comment]
@spacecataz: Should we add documentation to the trace2d Python functions documenting this? They're mostly there for the pybats functions, which handle the array allocation, but I can see people wanting to make use of the tracers. Then we can recommend that calling functions copy the field first if it's important to maintain it.

**Comment by henry2004y** [comment]
Is the reason that the Python object not get changed bacause of the `numpy.require` in
[trace2d.py](https://github.com/spacepy/spacepy/blob/4ced946a3b2fe7656c14baea4e4f8e83f706fc53/spacepy/pybats/trace2d.py#L30)?
