### ISSUE TITLE
spacepy.pybats.ImfInput.write can produce invalid time output

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#291]
The write method of spacepy.pybats.ImfInput rounds the microseconds when writing the time, as it writes milliseconds to the IMF file. If the microseconds are 999500 or greater, this rounds to 1000, which is treated (rightly) as invalid on read.

Suggestions:
- Rather than rounding, we could just truncate to milliseconds.
- It might be more accurate to convert to a numeric time, round, then back-convert and write out to the text file.

### Minimal example to reproduce issue:
```
from spacepy import pybats
imf = pybats.ImfInput()
for key in imf: imf[key]=[0]
imf['time'] = [dt.datetime(2017,9,6,16,42,36,999500)]
imf.write('testme.dat')
imf2 = pybats.ImfInput('testme.dat')
```

### Error message/Traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-59a42331f5c9> in <module>
----> 1 imf2 = pybats.ImfInput('testme.dat')

~/projects/env/lib/python3.6/site-packages/spacepy/pybats/__init__.py in __init__(self, filename, load, npoin
ts, *args, **kwargs)
   1323         # Load/create data vectors.
   1324         if filename and load:  # Load contents from existing file.
-> 1325             self.read(filename)
   1326         else:
   1327             units   = ['nT', 'nT', 'nT', 'km/s', 'km/s', 'km/s', 'cm^-3', 'K']

~/projects/env/lib/python3.6/site-packages/spacepy/pybats/__init__.py in read(self, infile)
   1508                     int(parts[4]), #min
   1509                     int(parts[5]), #sec
-> 1510                     int(parts[6]) * 1000 #micro seconds
   1511                     ))
   1512             for j, name in enumerate(self.attrs['var']):

ValueError: microsecond must be in 0..999999

```
The issue is that the data line has 1000 for the milliseconds, as can also be seen through pdb:
```
ipdb> parts
['2017', '09', '06', '16', '42', '36', '1000', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00'
]
```

### OS, Python version, and dependency version information:
```
Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
numpy=1.16.2
scipy=1.2.1
matplotlib=3.0.3
```

### Version of SpacePy
From git repo, last commit was March 19th.

**Comment by spacecataz** [comment]
It would be best to handle this via some conversion from date time to number, rounding, and returning.  However, this is non trivial as we are getting into issues of precision.  To wit, 

```
>>> from matplotlib.dates import date2num, num2date
>>> t
>>> array([datetime.datetime(2017, 9, 6, 16, 42, 36, 999500)], dtype=object)

>>> num2date(date2num(t))
[datetime.datetime(2017, 9, 6, 16, 42, 36, 999504, tzinfo=<matplotlib.dates._UTC object at 0x7fab096fbbe0>)]
```
We could get clever and write our own way to convert times to floats, but this doesn't seem worth the hassle right now.  The immediate solution is to remove the "round" when writing and just floor the millisecond values.

**Comment by jtniehof** [comment]
Any reason can't just do:
```
t = self.time[i]
ms = int(round(t.microsecond / 1000.))
if ms = 10000:
    ms = 0
    t += dt.timedelta(microseconds=1000)
out.write('{:%Y %m %d %H %M %S} {:03d} '.format(t, ms))
```

**Comment by spacecataz** [comment]
Re-addressing this now that I have "time".
I'm hesitant to drop an if clause inside a loop, especially as some of
these files get large (month long, minute or less time resolution)- could
slow down write speeds, and seems like a blunt tool for 0.5
millisecond difference.  If you strongly prefer this over dropping "round"
in favor of an "int" (that is, correcting via truncation instead of
rounding), let me know and I'll go that route.
