### ISSUE TITLE
Python 2.7 CI

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#30]
CI hangs on 2.7 with @drsteve 's latest trials. This might be related to #24 since both seem to be failures in fortan build. But we should ideally have travis running on 2.7, at least for now.

**Comment by jtniehof** [comment]
@drsteve , I'd love to get more into the Travis CI stuff but won't have time for a bit. If I make a branch with a heavily-instrumented version of setup.py, logging to a file or something, would you be able to pull that log to help figure out where it hangs?

**Comment by jtniehof** [comment]
OTOH on Windows right now I'm having it hang when linking irbempylib on 64-bit Python 2.7, so I might have a reproduction.

**Comment by drsteve** [comment]
That all looks very familiar. I'll fire up a new branch for doing CI with different package versions (#31 ) and I'll test 2.7 with an older version of numpy. If that fixes the hang on Travis then we can exclude the bad combo from testing and maybe set a version exclusion (#8 and #38 ) so users don't hit it (e.g. #24 ).

**Comment by jtniehof** [comment]
Updating from numpy 1.15.0 to 1.15.1 fixed it for me; the Fortran now compiles in Python 2.7 on Windows, 64-bit. I rolled back to 1.15.0 and the build hangs again...it's not the link, it's the compile step of f2py, compiling fortranobject.o.

Looks like we have a winner (loser), at least on the Windows front.

**Comment by drsteve** [comment]
Update in #31 
Testing now shows 2.7 passing with a variety of numpy versions, and I'm excluding 1.15.0 (which is the Travis default and is the likely culprit for the failure). When the updates for #31 are complete I'll submit a PR which should close both of these issues.
