### ISSUE TITLE
test coverage: coordinates

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#302]
At 73%. Kicking this up looks like it shouldn't be too rough.

**Comment by jtniehof** [comment]
- str function
- len for stuff that's not list/ndarray
- cases in convert labeled  "# only car2sph or sph2car is needed " and "# check if car2sph is needed first for oneralib compatibility" and "# 'car'"

**Comment by drsteve** [comment]
I'll take this, since it goes well with my overhaul of the backend.
