### ISSUE TITLE
test coverage: empiricals

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#306]
At 70%. Looks like a couple of untested functions that shouldn't be too hard to hit.

- getMagnetopause
- getExpectedSWTemp and its embedded functions
- getVampolaOrder

**Comment by balarsen** [comment]
@jtniehof , my report says 99%, what command did you run to evaluate?

I used `pytest --cov-report html --cov=emp test_empiricals.py`

**Comment by balarsen** [comment]
Strike this, operator error
` pytest --cov-report html --cov=spacepy test_empiricals.py` gives the 71%
