### ISSUE TITLE
test coverage: toolbox

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#313]
Down to 70%, including the integration tests. Lots of little exceptional cases to check, bigger chunks:

- quaternionRotateVector is untested
- update isn't tested and should probably go in the integration test; it calls a lot of the other stuff that isn't tested.
- assemble with sortKey specified

**Comment by jtniehof** [comment]
Self-assigning for update because I've been messing with it; the rest is up for grabs.

**Comment by drsteve** [comment]
I should write the quaternion rotation tests...

**Comment by jtniehof** [comment]
quaternion rotations moved to coordinates in #369, where I also added the rotation tests. @drsteve , feel free to self-assign here; if you think there should be more rotation tests, that would now be in #302.

**Comment by jtniehof** [comment]
- line 42: remove the dance around this import, just do the import
- tCommon valueerrors (may be hard to hit)
- loadpickle: we can't test the out of memory, but I think we only hit "if gzip" when gzip is true
- assemble: test with sortkey, remove superfluous else
- consider breaking out update and testing subpieces
- indsFromXrange
- boothisto: write a test of the plotting, look at test_plot_utils for the setup, this test will be in a new class
