### ISSUE TITLE
Nightly builds of CI

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#32]
#31 aside, we should _also_ catch when an updated version of a dependency breaks stuff. So can we have pinned versions on the pull request builds but also a nightly build that runs against master and the latest dependencies (and maybe even automatically opens a issue?)

**Comment by drsteve** [comment]
I just turned daily builds on, with the exception that it won't run if there's been another build in the intervening 24hrs. Thanks to @hugovk for pointing out where the Travis setting for cron jobs was.

This will just run the standard test setup on master, which currently pulls from pip so will have the latest stable releases of dependencies.

Re. automatically opening issues... [TravisBuddy](https://www.travisbuddy.com/) seems to be close, in that it automatically comments on PRs with the reason the Travis CI failed (using Travis' notifications). I won't close this yet, but it's at least part resolved.

**Comment by drsteve** [comment]
To stop this issue from going stale, I'd like to get thoughts on whether we should set up TravisBuddy, and if so, does that resolve this issue? If TravisBuddy isn't something we want then I move to close this issue as we have nightly builds and a new issue related to CI for Windows.

**Comment by jtniehof** [comment]
Let's try TravisBuddy and see how it goes. I'd still like to have auto-open issues when master fails, but that can be punted into the deep weeds of future enhancements.
