### ISSUE TITLE
h5py is a requirement or optional?

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#323]
h5py is called out in requirements.txt and setup.py as required. 

Yet in datamodel.py there is 
```
    try:
        import h5py as h5py
    except ImportError:
        raise ImportError('h5py is required to use HDF5 files')
```
in a few places. 

Thoughts on ripping out the above from datamodel.py?

Looking at spacepy 0fbb879

**Comment by jtniehof** [comment]
Closing per discusion in #324
