### ISSUE TITLE
FutureWarning numpy: arrays to stack must be passed as a "sequence" type such as list or tuple

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#325]
`FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
`

The warning is thrown by `test_toolbox.py:379` and `test_poppy.py:219`

The issue is really in `toolbox.bootHisto`, which is really an issue in  `poppy.boots_ci` at
https://github.com/spacepy/spacepy/blob/0fbb879a5d9f50fa2d22bf5b056ba60f1edac7b6/spacepy/poppy.py#L762
`gen` is a generator and this is what is depreciated. 

It would be solved by changing `gen` from a generator to a list comprehension. I suspect this is a benign change but I don't feel comfortable in poppy, @drsteve , @jtniehof  please have a look and comment. 

Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid
sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
numpy=1.18.4
scipy=1.4.1
matplotlib=3.2.1

spacepy 0fbb879a5d9f50fa2d22bf5b056ba60f1edac7b6

**Comment by jtniehof** [comment]
I have to dig in PoPPy for test coverage anyhow so I can look at it.

**Comment by jtniehof** [comment]
This was fixed (somewhat incidentally) in #372
