### ISSUE TITLE
Revert to USNO leap seconds

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#341]
#338 changes our leapsecond retrieval to a secondary NASA source. Hopefully at some point the USNO primary source will be back online and we should revert to it.

**Comment by drsteve** [comment]
FYI, USNO seems to have their webpage back up... only change is they've moved to https.
[https://maia.usno.navy.mil/ser7/tai-utc.dat](https://maia.usno.navy.mil/ser7/tai-utc.dat)
