### ISSUE TITLE
Upstream failure in test_toolbox.SimpleFunctionTests in WSL

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#344]
```
python test_toolbox.py -v

test_timeout_check_call (__main__.SimpleFunctionTests)
Make sure check_call replacement handles timeout ... sleep: cannot read realtime clock: Invalid argument
ERROR
```

Do we want to do anything about this or not? Apparently known upstream: https://github.com/microsoft/WSL/issues/4898

### Minimal example to reproduce issue:

```
In [4]: import subprocess

In [5]: subprocess.check_call(['sleep', '2'])
sleep: cannot read realtime clock: Invalid argument
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-5-4f72d59a5ac3> in <module>
----> 1 subprocess.check_call(['sleep', '2'])

~/miniconda3/envs/python3/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    361         if cmd is None:
    362             cmd = popenargs[0]
--> 363         raise CalledProcessError(retcode, cmd)
    364     return 0
    365

CalledProcessError: Command '['sleep', '2']' returned non-zero exit status 1.

```

Linux-4.4.0-18362-Microsoft-x86_64-with-debian-bullseye-sid
sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
numpy=1.18.4
scipy=1.4.1
matplotlib=3.2.1
spacepy=23e3062740d8a871c25a2b884dff1a675826932e

**Comment by jtniehof** [comment]
Let's keep an eye on it for now and see if the fix actually rolls out. If not we can probably bash a workaround.

**Comment by jtniehof** [comment]
It looks like this is fixed upstream now and don't think it's worth a workaround for people who won't upgrade WSL. Closing.
