### ISSUE TITLE
about installing spacepy

### ISSUE THREAD

**Issue by FrankMelon1** [spacepy/spacepy#353]
I would like to thank you first for the great scientific contribution made in the paper.
I got an error when trying to run the demo, This is the error message got:

(SPIN) wutao@Asina:~/SPIN/spacepy$ python setup.py install --user
running install
running build
C compiler: gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/spacepy
creating build/temp.linux-x86_64-3.6/spacepy/libspacepy
compile options: '-c'
gcc: spacepy/libspacepy/ctrace2d.c
gcc: spacepy/libspacepy/randomkit.c
gcc: spacepy/libspacepy/cn_solver.c
gcc: spacepy/libspacepy/poppy.c
gcc: spacepy/libspacepy/toolbox.c
creating build/lib
creating build/lib/spacepy
gcc -pthread -shared -L/home/wutao/anaconda3/envs/SPIN/lib -Wl,-rpath=/home/wutao/anaconda3/envs/SPIN/lib,--no-as-needed build/temp.linux-x86_64-3.6/spacepy/libspacepy/cn_solver.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/ctrace2d.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/poppy.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/randomkit.o build/temp.linux-x86_64-3.6/spacepy/libspacepy/toolbox.o -lm -o build/lib/spacepy/libspacepy.so
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running build_py
copying spacepy/LANLstar.py -> build/lib/spacepy
copying spacepy/__init__.py -> build/lib/spacepy
copying spacepy/ae9ap9.py -> build/lib/spacepy
copying spacepy/coordinates.py -> build/lib/spacepy
copying spacepy/data_assimilation.py -> build/lib/spacepy
copying spacepy/datamanager.py -> build/lib/spacepy
copying spacepy/datamodel.py -> build/lib/spacepy
copying spacepy/empiricals.py -> build/lib/spacepy
copying spacepy/lib.py -> build/lib/spacepy
copying spacepy/omni.py -> build/lib/spacepy
copying spacepy/poppy.py -> build/lib/spacepy
copying spacepy/radbelt.py -> build/lib/spacepy
copying spacepy/realtime.py -> build/lib/spacepy
copying spacepy/rst.py -> build/lib/spacepy
copying spacepy/seapy.py -> build/lib/spacepy
copying spacepy/spacepy_EnKF.py -> build/lib/spacepy
copying spacepy/time.py -> build/lib/spacepy
creating build/lib/spacepy/irbempy
copying spacepy/irbempy/__init__.py -> build/lib/spacepy/irbempy
copying spacepy/irbempy/irbempy.py -> build/lib/spacepy/irbempy
creating build/lib/spacepy/pycdf
copying spacepy/pycdf/__init__.py -> build/lib/spacepy/pycdf
copying spacepy/pycdf/const.py -> build/lib/spacepy/pycdf
copying spacepy/pycdf/istp.py -> build/lib/spacepy/pycdf
creating build/lib/spacepy/plot
copying spacepy/plot/__init__.py -> build/lib/spacepy/plot
copying spacepy/plot/apionly.py -> build/lib/spacepy/plot
copying spacepy/plot/carrington.py -> build/lib/spacepy/plot
copying spacepy/plot/colourmaps.py -> build/lib/spacepy/plot
copying spacepy/plot/spectrogram.py -> build/lib/spacepy/plot
copying spacepy/plot/utils.py -> build/lib/spacepy/plot
creating build/lib/spacepy/pybats
copying spacepy/pybats/__init__.py -> build/lib/spacepy/pybats
copying spacepy/pybats/bats.py -> build/lib/spacepy/pybats
copying spacepy/pybats/batsmath.py -> build/lib/spacepy/pybats
copying spacepy/pybats/dgcpm.py -> build/lib/spacepy/pybats
copying spacepy/pybats/dipole.py -> build/lib/spacepy/pybats
copying spacepy/pybats/gitm.py -> build/lib/spacepy/pybats
copying spacepy/pybats/interact.py -> build/lib/spacepy/pybats
copying spacepy/pybats/kyoto.py -> build/lib/spacepy/pybats
copying spacepy/pybats/pwom.py -> build/lib/spacepy/pybats
copying spacepy/pybats/qotree.py -> build/lib/spacepy/pybats
copying spacepy/pybats/ram.py -> build/lib/spacepy/pybats
copying spacepy/pybats/rim.py -> build/lib/spacepy/pybats
copying spacepy/pybats/trace2d.py -> build/lib/spacepy/pybats
creating build/lib/spacepy/toolbox
copying spacepy/toolbox/__init__.py -> build/lib/spacepy/toolbox
creating build/lib/spacepy/data
copying spacepy/data/SEA_epochs_OMNI.txt -> build/lib/spacepy/data
copying spacepy/data/spacepy.mplstyle -> build/lib/spacepy/data
copying spacepy/data/spacepy_altgrid.mplstyle -> build/lib/spacepy/data
copying spacepy/data/spacepy_polar.mplstyle -> build/lib/spacepy/data
copying spacepy/data/tai-utc.dat -> build/lib/spacepy/data
creating build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_OPDyn.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_OPQuiet.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_RAMSCB.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_T01QUIET.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_T01STORM.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_T05.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_T89.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/LANLstar_T96.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_OPDyn.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_OPQuiet.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_T01QUIET.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_T01STORM.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_T05.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_T89.net.gz -> build/lib/spacepy/data/LANLstar
copying spacepy/data/LANLstar/Lmax_T96.net.gz -> build/lib/spacepy/data/LANLstar
creating build/lib/spacepy/data/TS07D
creating build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamebhr1.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamebhr2.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamebhr3.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamebhr4.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamebhr5.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_11.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_12.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_13.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_14.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_21.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_22.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_23.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_24.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_31.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_32.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_33.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_34.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_41.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_42.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_43.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_44.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_51.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_52.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_53.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_e_54.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_11.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_12.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_13.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_14.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_21.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_22.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_23.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_24.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_31.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_32.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_33.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_34.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_41.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_42.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_43.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_44.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_51.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_52.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_53.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
copying spacepy/data/TS07D/TAIL_PAR/tailamhr_o_54.par -> build/lib/spacepy/data/TS07D/TAIL_PAR
customize Gnu95FCompiler
Could not locate executable gfortran
Could not locate executable f95
Traceback (most recent call last):
  File "setup.py", line 1004, in <module>
    setup(**setup_kwargs)
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/site-packages/numpy/distutils/command/install.py", line 60, in run
    r = old_install.run(self)
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 775, in run
    self.compile_irbempy()
  File "setup.py", line 509, in compile_irbempy
    f2py_env, fcompexec = f2py_options(fcompiler, self.distribution)
  File "setup.py", line 193, in f2py_options
    fcomp.customize(dist)
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/site-packages/numpy/distutils/fcompiler/__init__.py", line 463, in customize
    self.find_executables()
  File "/home/wutao/anaconda3/envs/SPIN/lib/python3.6/site-packages/numpy/distutils/fcompiler/__init__.py", line 352, in find_executables
    raise CompilerNotFound('%s: f90 nor f77' % ctype)
numpy.distutils.fcompiler.CompilerNotFound: gnu95: f90 nor f77

Do you know how to solve this issue?
Thanks a lot for your support

**Comment by jtniehof** [comment]
It looks like there isn't a Fortran compiler installed. See the [Linux install directions](https://spacepy.github.io/install_linux.html) for details, including installing a compiler or skipping all Fortran code.

**Comment by jtniehof** [comment]
Since I haven't heard back, hopefully that information helped. Closing this as not an issue; feel free to reopen or open another if there are any further difficulties.
