### ISSUE TITLE
Ticktock with isotime input fails on non-str input

### ISSUE THREAD

**Issue by ademekhov** [spacepy/spacepy#354]
My issue is that the result of HDF5 import into datamodel data type changed between 0.1.6 (which I use under Python2.7) and 0.2.1 (which I am trying to use under Python3).

### Minimal example to reproduce issue:

```
from __future__ import print_function

import os
os.putenv("CDF_LIB", "/usr/local/cdf/lib")
import spacepy.datamodel as dm
import spacepy.time as spt

hd = os.path.expanduser('~')

fn = '{}/data/RBSP/A/MagEphem/2015/rbspa_def_MagEphem_T89Q_20151225_v1.0.0.h5'.format(hd)
sd = dm.fromHDF5(fn)
print ('type(sd[\'IsoTime\'] is {}'.format(type(sd['IsoTime'])))
print ('type(sd[\'IsoTime\'][0] is {}'.format(type(sd['IsoTime'][0])))
ep = spt.Ticktock(sd['IsoTime'])
```

### Error message/Traceback:

```
>>> type(sd['IsoTime'] is <class 'spacepy.datamodel.dmarray'>
type(sd['IsoTime'][0] is <class 'numpy.bytes_'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrei/lib/python/scripts/tt_test.py", line 17, in <module>
  File "/usr/local/lib/python3.8/dist-packages/spacepy/time.py", line 236, in __init__
    elif self.data[0] > 1e13:
TypeError: '>' not supported between instances of 'numpy.bytes_' and 'float'
 ...
```

### Version of SpacePy

The error is produced when running 0.2.1. When I am running 0.1.6 under Python 2.7, the result for type(sd['IsoTime'][0]) is <class numpy.string_>, and then it is easily converted to TickTock.

**Comment by jtniehof** [comment]
Minimum broken example:
`spacepy.time.Ticktock(b'2020-01-01T00:00:00')`

The problem is that we're always writing the time as string, so bytes in Python 2 and unicode/new str in Python 3. Similarly, on Python 2:
`spacepy.time.Ticktock(u'2020-01-01T00:00:00')`

These should be easy to fix and I'll give it a whirl. I'm going to update the title.
