### ISSUE TITLE
spectrogram class hides spectrogram module

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#358]
`plot.spectrogram` contains a class `spectrogram`. However since top-level `plot` does `from .spectrogram import *` it's impossible to get at the `plot.spectrogram` module. This makes the autodocs not work correctly.

My preference would be to not bring everything into the `plot` namespace, but that's not the smallest possible change to fix this issue. Otherwise we need to make the names not clash, and I can see two options:

1. Rename the `spectrogram` module to `spect` (or similar).
2. Rename the `spectrogram` class to `Spectrogram`.

The advantage of 1 is that it doesn't change the current behavior. 2 is more consistent with convention (classes are usually capitalized) but it's just not going to be possible to have lowercase `spectrogram` refer to both the class and the module for a transition period. If we do 2, my suggestion would be to add the `Spectrogram` name for the class to both `plot` and `plot.spectrogram` and then make any instantiation of `spectrogram` raise a DeprecationWarning so people know to change the caps. Then on a later release we can remove the `spectrogram` class name, exposing the `spectrogram` module.

I'm bringing this up now so we can do the deprecation in 0.2.2 and possibly make the change in 0.3.0, so then I can start working on getting the docs happier.

**Comment by drsteve** [comment]
I vote for option 2. It's more work, but I think it's the *right* fix.

**Comment by balarsen** [comment]
I think option 2 is a good also. We should also not forget #278 as I wrote spectrogram and can't ever use it these days.

**Comment by jtniehof** [comment]
Okay, I'll work on a PR to add Spectrogram and mark spectrogram as deprecated.

**Comment by jtniehof** [comment]
#450 does the first part of this for 0.2.2

**Comment by jtniehof** [comment]
Note making the docs all pretty is *not* part of this issue...but fixing this issue is a prereq for fixing the docs.
