### ISSUE TITLE
test_AlphaOfK hangs with Python 3.8 and numpy 1.19.0 in CI

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#364]
We've had occasional Travis failures where the tests hang and eventually Travis kills for lack of output. It seems to always be the last build, which is Python 3.8 and numpy 1.19.0. With #363 I can see that, at least once, it's happened in test_irbempy.IRBEMBigTests.test_AlphaOfK. Restarting seems to work, so it might be an issue with running too many builds at once, but for now it's worth hammering on Py3.8/numpy 1.19 to see if it can be reproduced outside of CI.

**Comment by jtniehof** [comment]
1.19 was just released a few days ago (it's not even on the front page of numpy.org yet) and this did start showing up a few days ago, so might be a 1.19 issue. We are building a test with 3.7 and 1.19 as well, so it would be a 3.8 + numpy 1.19 issue.

**Comment by jtniehof** [comment]
3.8 and numpy 1.17.5 just hung on the daily build, can't tell where since #363 isn't merged yet.

**Comment by jtniehof** [comment]
There's definitely something not properly cleaned up (3.8, numpy 1.18.5), might or might not be related...

```
python test_irbempy.py -v IRBEMBigTests.test_AlphaOfK
test_AlphaOfK (__main__.IRBEMBigTests)
test calculation of eq. pitch angle from K (regression) ... /home/jtniehof/miniconda/envs/py38/lib/python3.8/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.Pool state=RUN pool_size=8>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
```

**Comment by jtniehof** [comment]
3.8 and 1.19 just failed again (job 851.10, will kick to restart), in AlphaOfK.

**Comment by jtniehof** [comment]
853.9 and 853.10, both Python 3.8 with numpy 1.17.5 and 1.19.0 respectively, both failed in AlphaOfK, which does seem to indicate it's not just "one out of ten" and probably an issue with Python version not numpy.

**Comment by drsteve** [comment]
Looks like it's Python 3.8, see https://bugs.python.org/issue38744. There are other reports that seem similar, including issues with dask. It looks like we might be able to work around it though.

**Comment by jtniehof** [comment]
Nice find. Thanks; that should be fairly easy to work around.

**Comment by jtniehof** [comment]
If my skim of that issue is correct, it does suggest the ResourceWarning is related.

**Comment by jtniehof** [comment]
I haven't been able to reproduce this with Python 3.8.3 on either my laptop or a big server, when running test_irbem in a loop (50 times). I'm now trying it with a 50-loop of test_all. If that doesn't reproduce I'll just fix the ResourceWarning and hope it does the trick.

**Comment by jtniehof** [comment]
The resource error is because the alpha of K test calls get_Lstar in such a way as to not need multiple CPUs, but get_Lstar opens the pool anyhow. Regardless, the pool is never properly closed, so that's probably the issue for #351. PR incoming in a bit.

**Comment by drsteve** [comment]
Do we want to wait to close this one, just in case we hit more hangs? Or optimistically assume that #372 fixed it and close?

**Comment by jtniehof** [comment]
Let's leave it open for a few more daily builds to be sure.

**Comment by jtniehof** [comment]
We've had several good cron builds and lots of PR builds since this was integrated on master, so I think we're good to close.
