### ISSUE TITLE
matplotlib 3.3 breaks spacepy <=0.2.1

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#381]
Our cron build of master has failed three days running. Python 2.7 on bionic is fine, 3.5 on xenial is fine, but 3.6, 3.7, 3.8 on bionic have test failures. I haven't done a diff of the outputs but they seem to all be nearly (but not exactly) the same. A lot of it is related to functions that use OMNI input so maybe there's something weird with the test db there.

All of this has succeeded before so there's probably some change in the Travis environment exposing some sort of fragility. There are also some numpy warnings showing up, and I got all the Python 3.8 and  numpy warnings squashed in #372, so our version of numpy may have shifted.

**Comment by jtniehof** [comment]
I can't deal with this tonight but will try to carve out time tomorrow.

**Comment by drsteve** [comment]
It's matplotlib.
I just... [why would they do this?](https://matplotlib.org/3.3.0/users/whats_new.html#dates-use-a-modern-epoch)`*`

Short story: The version bumped to 3.3.0. Matplotlib's `date2num` and `num2date` have changed, without any future or deprecation warnings, AFAIK. Looks like the "easiest" fix is resetting the epoch in the rcParams. I think we'll need to flag _*very clearly*_ that spacepy <=0.2.1 is not compatible with MPL>=3.3.

`*` Okay, I know why they would do it. The change itself is good, but I am extremely unimpressed that they dropped it in without warnings in previous versions and broke compatibility. I'd like to have seen them introduce the settable epoch first and raise a warning that it was changing, then change in a later release. I imagine we aren't the only folks downstream who are going to be affected.

**Comment by jtniehof** [comment]
That's mind-boggling. It's such a major change. The 3.2.0 docs explicitly define it as days-since 01-01-01, with no mention of "don't rely on this." Getting the code to work on <3.3 and >=3.3 is probably going to be a pain...I'm not sure we want to call `set_epoch` all the time (and potentially break other code.) `get_epoch` doesn't even exist in 3.2.

**Comment by balarsen** [comment]
To me this implies that we should just rewrite where ever we use `date2num`, `num2date` to use `spacepy.time`,

**Comment by drsteve** [comment]
Some of the uses won't need changing because the specific value doesn't matter as long as matplotlib handles it consistently.
Others will need changing over...

For example, in `spacepy.time` the `randomDate` function uses `date2num` and `num2date` for a roundtrip conversion so it can sample uniform random numbers on a timeline. That shouldn't be affected.
The other location in `spacepy.time` that's affected is the `RDT` time system is defined to be basically what matplotlib used to use in `num2date` and `date2num`. So that will need a rewrite.

It's probably less work than it looks like from just grepping.

**Comment by jtniehof** [comment]
Is there a reason to keep RDT backward-compatible with matplotlib in terms of ignorance of leap seconds? i.e. are we okay with having a second being a smaller fraction of a day on days that end with a leap second? Because if so, I think we just do #319 and #320, make TAI/MJD the "primary" timebases, and redefine RDT in terms of MJD, and that solves our time-related issues. I'm happy to take a crack at it.

That also would let `spacepy.time` drop the matplotlib requirement, which I rather like.

Other places that need to explicitly interact with matplotlib obviously need more care, but I think a lot of our usage of num2date/date2num was for convenience, and we can replace as appropriate.

**Comment by drsteve** [comment]
Using one of the linear timebases as the reference makes sense. RDT ("Rata Die") seems to be less well defined in terms of the impact of leap seconds, and we certainly don't provide a clear definition in documentation. So to answer your question, I think your proposal seems fine to me.

**Comment by balarsen** [comment]
To fix the build can we just force an install of matplotlib<3.3? To move forward a bit until we resolve this?

**Comment by jtniehof** [comment]
Yep, we can. I was hoping to avoid it but honestly the time rework is going to be more than a matter of an hour (I'm working on it!) and there's no sense standing still until then.

**Comment by jtniehof** [comment]
There's also #366 which meant messing with CI was in the cards but honestly, let's stop the bleeding.
