### ISSUE TITLE
Ticktock: Handle time when TAI second != UTC second

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#393]
From 1960-1972, the UTC second was not equal in length to the TAI (and SI) second. This involved both fractional leap seconds and a UTC second being longer than the SI second. In Ticktock, we currently handle this by simply truncating TAI-UTC to the nearest integer wherever there's an update in the USNO tai-utc file, and maintain TAI second == SI second.

There are a few ways this could be handled:

1. The "right way", read the appropriate rate from the file and maintain a non-integral offset within this period.
2. Implement "stepped atomic time," which has more frequent fractional leapseconds but no rate adjustment.
3. Fudge the leap second data between 1960 and 1972, where we insert leap seconds according to the current rules to keep UTC-UT1 within 0.9s. Basically "playing IERS." This sounds terrible but it's actually not very different from what we're doing: some of the records in tai-utc result in no leap second treatment from Ticktock (pure rate changes and/or small fractional leaps), whereas some result in two (end of 1963: TAI-UTC is 3.2, previous record is 1.9, truncation leads to two leap seconds; see #390)
4. Document that if you want absolute time precision before 1972 *and* perfect conversion between UTC and TAI, you're barking up the wrong tree. Note that before 1960 UTC technically didn't exist so it's already somewhat hypothetical...we really don't want to handle "railroad time" in SpacePy.

**Comment by jtniehof** [comment]
The 10 second gap at the end of 1971 is _really_ annoying so we should probably do something about this.

**Comment by jtniehof** [comment]
I'm adding this to the 0.2.2 because if we expect to change behavior, it's probably best to do it in a release with the other mess of time changes.

**Comment by jtniehof** [comment]
After #390 is merged, my intention is to resolve this, probably but not necessarily with option 3. [NIST claims](https://www.nist.gov/pml/time-and-frequency-division/leap-seconds-faqs#often) a ten-second jump at the start of 1972, which doesn't seem to match the value with the "rubber second" but I'll have to play with plotting that properly. I think what they might mean is that TAI-UTC was 10s at that point (which is correct, the jump is six seconds without a rubber second.)

Getting the fractional value correct to work off: figure on page 80 [here](https://tf.nist.gov/general/pdf/1168.pdf); also [this table](https://www.iers.org/IERS/EN/Science/EarthRotation/UT1-TAI.html?nn=12932) gives the difference between UT1 and TAI. Note that first reference, page 83, states TAI is only good to about 10ns (at writing in 1991). [This monograph](https://nvlpubs.nist.gov/nistpubs/Legacy/MONO/nbsmonograph140.pdf) (page 8) gives the "offset rate", or the ratio between UTC and TAI as a difference from unity. That also has the mention of stepped atomic time, but little on detail...I don't think reproducing that is going to be an option, axing option 2 above. According to [this monograph](https://tf.nist.gov/general/pdf/1796.pdf) (page 109/sheet 112), the length of the second was set at the start of each year, and fractional leapseconds introduced when UTC - UT2 was over 0.1s.

Also per NIST, the leap second gets added when UTC - UT1 exceeds 0.4 seconds, so that's basically our figure of merit.

I'm going to draw the line at going back to 1620 but there are [UT1 values](https://stjarnhimlen.se/comp/time.html) back that far!

What I am _not_ seeing is anybody else retroactively applying post-1972 rules to the rubber second era. This seems odd to me, since it seems to be the most obvious approach.

**Comment by jtniehof** [comment]
Having done the math, UTC runs _backwards_ in the rubber second era, that is, there are negative (fractional) leap seconds and thus the same TAI corresponds to multiple UTCs. I'm trying to get my head around this because of course TAI - UTC is calculated based on UTC and it might be that one of the pair is an invalid UTC time, much like 23:59:59 is an invalid UTC time on a day with a negative leap second in the modern era. But this is confirming I don't want to do things "right" before 1972.

Dates of note: 1955 for start of atomic time, 1958 for first attempts of NIST to connect atomic time to what would become UTC (TAI == UT1 here, and there are fractional steps/rates starting from 1958), 1961 for start of UTC rubber-second era, 1972 for start of whole leapsecond.

Attached is TAI - UTC for the atomic clock era through modern UTC (1958 through 1973). Blue line is TAI - UTC based on the rubber second definition and assumed 0 before 1961. Orange X are measured TAI - UT1. Green dashed line is based on inserting a leapsecond every January or July when TAI - UT1 exceeds 0.4 (the modern standard). Red dot-dashed line is based on inserting a leapsecond when TAI - UTC (where UTC is based on the rubber second) exceeds 0.5. Purple dotted line is current Ticktock.

I think the green dotted line makes the most sense.

![rubber_seconds](https://user-images.githubusercontent.com/196315/111037621-eb6c4e00-83f2-11eb-8d4a-b3dd3d220adb.png)

**Comment by jtniehof** [comment]
I suppose it would be possible to do something like "decide on whether or not there's a leap second at a particular Jan/July based on minimizing the RMS error with UT1 (or UTC) between that and the next leapsecond opportunity." I also only introduced ls at Jan/July in the above plot, since we're cheating anyhow we could do the first of any month. But the green line is "apply today's rules in the past" and it seems to do pretty darn good.

**Comment by jtniehof** [comment]
Code that makes the above plots is in #520 or https://github.com/jtniehof/spacepy/blob/rubber_second/developer/scripts/rubber_seconds.py

**Comment by drsteve** [comment]
Thoughts:
- There's an appeal to the "rubber second" approach, but the negative fractional leap seconds are giving me pause for thought. I think this is the most _technically correct_ answer, but I don't like it. I think my issue is that it's a running offset rather than fractional leap seconds _as we might currently think of them_ (or equivalently, every day has a fractional leap second, which might be worse).
- Applying the present standard backwards in time gives a good fit to the actual curve and is easy to understand and document. There also a possible argument to be made that UTC _as defined currently_ is an approximation of UT1 to within a second, where for '61-'72 UTC approximated UT2, which no-one uses. So this is aiming for consistency in a few ways, even though it's not exactly as defined by the UTC-TAI tables.

I think this makes me _Team Green_.

**Comment by jtniehof** [comment]
Implementing the rubber second (blue line) isn't really a credible
possibility without fundamentally reworking how we handle tai-utc. Maybe
that would be a win anyhow but I'd like to move on from time for a bit.
Green and red are the readily implementable solutions.

**Comment by jtniehof** [comment]
Since I'm getting back to the design idea, pulling information from #520: CDF TT2000 exactly matches the actual rubber-second UTC line.

The blue line is one-millisecond resolution conversion _from_ UTC _to_ CDF TT2000 (TAI-related). The orange is from TT2000 to UTC, but put on the same axes. So it's clear that the negative leap second means 1961-07-31T23:59:59.960 isn't a valid UTC time, but CDF will still accept it and result in a double-valued TAI conversion. Since the actual fractional leapsecond wasn't applied until 1961-08-01T00:00:00.000, that suggests the time was retroactively redefined. So did that mean at the tick of 1961-08-01T00:00:00.000 it was proclaimed to be 1961-08-01T00:00:00.050 and so _those_ are the ones that should be skipped?
![Figure_1](https://user-images.githubusercontent.com/196315/112158591-b3b59100-8bbe-11eb-8a11-a28b2c03879a.png)
