### ISSUE TITLE
Transfer CI to travis.com

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#418]
I got a note from Travis that everything needs to transfer from travis.org to travis.com. There's a link to how-to: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

On first glance this *might* already be done (clicking on our build status brings us to travis-ci.com) but it's not obvious if that's sufficient evidence....@drsteve ?

**Comment by drsteve** [comment]
I recall some info from Travis a while back suggesting that they were auto-migrating projects. It's also likely that any references to the old ".org" domain vanished when we changed from the old webhooks method of triggering the CI to the newer Travis integration. 
I'll circle back round to this and take a closer look when I get some more time. I suspect we're fine though.

**Comment by jtniehof** [comment]
Superseded by #455 .
