### ISSUE TITLE
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#42]
New warning that appeared in python 3.7.0

This one is in [time.py](https://github.com/spacepy/spacepy/blob/master/spacepy/time.py)

```
/Users/balarsen/.local/lib/python3.7/site-packages/spacepy/time.py:228: DeprecationWarning: 
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, 
and in 3.8 it will stop working
  if not isinstance(dtype, collections.Callable):
```

The offending code is `collections.Callable`. This should instead be:
```
import collections.abc
collections.abc.Callable
```

Possible that pycdf will have the issue as well. There are a lot of `collections.MutableSequence`, `collections.MutableMapping`, etc in there.

**Comment by jtniehof** [comment]
In most of these we can probably do:
```
try:
    import collections.abc as collections
except ImportError:
    import collections
```

Not my fave because I like to give precedence to the new naming, but it's harder to do that (and means editing all the references now instead of later):
```
import collections
try:
    import collections.abc
except ImportError:
    collections.abc = collections
```

We should probably pick one of these styles (or a different one) and stick with it. Absolutely not:
```
try:
    import collections.abc as cabc
except ImportError:
    import collections as cabc
```
which is a horrible PEP-8 violation.

**Comment by drsteve** [comment]
Bumping this one as we it seems like an easy fix as soon as we pick a solution.

Noting that we only really have a dozen instances to correct (go ahead, grep for them, it's really not so bad), my vote would be to use the form
```
try:
    from collections.abc import MutableSequence
except ImportError:
    from collections import MutableSequence
```

It's not violating PEP8, and I'd prefer that to the solutions above. I don't like the mental redirection in making `collections.abc` point to `collections` under older versions of Python. And the first solution loses the base collections namespace (in case we wanted it).

**Comment by jtniehof** [comment]
I don't like from imports but I agree it's probably the least-bad. PR to come.
