### ISSUE TITLE
Minimum numpy/scipy versions are not documented consistently

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#431]
### numpy
On the first line of `requirements.txt` it has `numpy>=1.10,!=1.15.0`
Documentation (`Doc/source/dependencies.rst` and `Doc/source/dep_versions.rst`) is aligned with `requirements.txt`
**_But_**, in the dependencies section of `README.md` the limits are given as `numpy (>=1.6, !=1.15.0)`

### scipy
On the second line of `requirements.txt` it has `scipy>=0.11`
As for `numpy`, the documentation is aligned with the `requirements.txt`
**_But_**, in the dependencies section of `README.md` the limits are given as `scipy (>=0.10)`

### suggested fix
1. Assuming `requirements.txt` is correct then the `README.md` text should be corrected
2. If the minimum `numpy` version supported is 1.10, then there's at least 1 special case that can be cleaned up in code (maybe more)
   - In `test_coordinates.py`, `test_quaternionToMatrix_nasty` special cases for `numpy`<1.8 for the determinant calculation.

### version
SpacePy master: (issue filed with commit be805de as HEAD)

**Comment by jtniehof** [comment]
Yep, in #420 I didn't think about README.md, so that needs to be updated.

I also didn't find all cases where we had fixes for early versions. I'm sure they'll be around for some time, and they should be removed as we find them.
