### ISSUE TITLE
Crash on getMPstandoff for large array of times

### ISSUE THREAD

**Issue by Caseyb87** [spacepy/spacepy#445]
Python crashes with an OSError when reading in Shue magnetopause standoff distances for a large array of times (in a for loop). 

Note: this could be an error in my coding, in which case I sincerely apologize! I'm not too proficient at Python debugging yet. And apologies if this is covered in another issue.

### Minimal example to reproduce issue:

```
for index, t in enumerate(sc_data["datetimes"]):
        #Need to convert numpy datetime64 into spacepy "Tick" (doesn't accept dt64)
        tick = spt.Ticktock(np.datetime_as_string(t, unit="s"), 'ISO')
        #Get Shue magnetopause standoff location
        mp_standoff = emp.getMPstandoff(tick)
```
where sc_data is a dictionary of spacecraft data and the datetimes key is 36656883 elements in length.

I don't know exactly at what element the crash occurs.

### Error message/Traceback:

```
Traceback (most recent call last):

  File "c:\users\userdirectory\userfilename.py", line 125, in <module>
    sc_data = create_magnetosheath_data_file(magnetosheath_data_filename)

  File "c:\users\userdirectory\userfilename.py", line 98, in create_magnetosheath_data_file
    mp_standoff = emp.getMPstandoff(tick)

  File "C:\Users\username\Anaconda3\lib\site-packages\spacepy\empiricals.py", line 309, in getMPstandoff
    omni = om.get_omni(ticks, dbase=dbase)

  File "C:\Users\username\Anaconda3\lib\site-packages\spacepy\omni.py", line 265, in get_omni
    omnivals[key] = dmarray(hfile[key][sl_op]) #TODO: add attrs from h5

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "C:\Users\username\Anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5d.pyx", line 182, in h5py.h5d.DatasetID.read

  File "h5py\_proxy.pyx", line 130, in h5py._proxy.dset_rw

  File "h5py\_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread

OSError: Can't read data (file read failed: time = Thu Nov 19 12:06:12 2020
, filename = 'H:\.spacepy\data\omnidata.h5', file descriptor = 4, errno = 22, error message = 'Invalid argument', buf = 00000212817D7518, total read size = 65536, bytes this sub-read = 65536, bytes actually read = 18446744073709551615, offset = 6260316)
```

### OS, Python version, and dependency version information:

```
Windows-10-10.0.19041-SP0
sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
numpy=1.19.1
scipy=1.5.0
matplotlib=3.3.1
```
### Version of SpacePy

0.2.1

**Comment by jtniehof** [comment]
That's not really a complete example to reproduce, since it assumes `sc_data` already exists, so I can't try it here.

It looks like the omni file is corrupt somehow. Can you try something bog simple like this:
```python
import spacepy.time
import spacepy.omni
t = spacepy.time.Ticktock(['2010-01-01'])
spacepy.omni.get_omni(t)
```

If that fails, try running the update for just the Qin-Denton files:
```python
import spacepy.toolbox
spacepy.toolbox.update(omni=True)
```

and then try the `get_omni` line again.

**Comment by Caseyb87** [comment]
> 
> 
> That's not really a complete example to reproduce, since it assumes `sc_data` already exists, so I can't try it here.
> 

Yep, apologies. I didn't really know how I could post anything more useful.


> Can you try something bog simple like this:
> 
> ```python
> import spacepy.time
> import spacepy.omni
> t = spacepy.time.Ticktock(['2010-01-01'])
> spacepy.omni.get_omni(t)
> ```
> 

That worked fine. 

> It looks like the omni file is corrupt somehow.

It was freshly installed and updated yesterday (new to spacepy, hence the recent topics here!). I'm currently running the code again (for a fourth time) but printing out the index of completed runs. Hopefully that'll either point to a specific issue in the omni file or rule that out.

**Comment by Caseyb87** [comment]
My issue may be related to this: https://groups.google.com/g/h5py/c/oRdOlECujx0

And appears to be a hdf5 error - rather than an a spacepy issue. I've reconfigured spacepy to use a local disk for the OMNI data store which will hopefully fix.

**Comment by jtniehof** [comment]
Thanks. That means something else weird is going on; it'll take me some time to dig a little deeper. I thought it might relate to #371 but this shouldn't be touching irbem (and it's not failing in IRBEM.)

**Comment by jtniehof** [comment]
Ah, good find. You might be able to get around it by only making one call to the OMNI, then the HDF5 consistency should be less of an issue. Something like this:
```python
import numpy
import spacepy.time
import spacepy.empiricals

# of course you'd use sc_data["datetimes"] here....
dt = numpy.arange('2005-02', '2005-03', dtype='datetime64[D]')
tt = spacepy.time.Ticktock(numpy.datetime_as_string(dt))
mp_standoff = spacepy.empiricals.getMPstandoff(tt)
```

Then you can iterate over `mp_standoff` (or an index that you apply to it and whatever else.)

**Comment by Caseyb87** [comment]
Thank you. I've done as you suggested (as well as moving the omni data to a local drive) and the code completed successfully.

Seeing as this is unlikely to be a spacepy issue, I'll close.
