### ISSUE TITLE
datamodel.readJSONheadedASCII could allow file to be gzip

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#448]
It would be a decent use case for `datamodel.readJSONheadedASCII` to accept gzip input files. 

The function works very well but the ability to read a `*.gz` file would be a simple and nice addition.

**Comment by jtniehof** [comment]
Or .zip, for that matter. loadpickle already does this sort of thing, so adapting that wouldn't be too bad.

**Comment by balarsen** [comment]
have to update `readJSONMetadata()` and `readJSONheadedASCII`. Likely will leave writing a zip or gzip for another issue.

**Comment by drsteve** [comment]
I support this enhancement. NOAA has started serving the GPS particle data as gzipped JSON-headed ASCII.
The only questions would be about whether we want to have auto-detection, or keyword specification (or some combination), for handling compressed files.

One of the handy features in `readJSONheadedASCII` is the abiliy to read multiple files when a list of filenames is passed in...  so, for example, how would we handle the (all too likely) case of a list of input files where one is unzipped and the rest are still compressed?

**Comment by balarsen** [comment]
@drsteve thanks for the note, I will make sure that doesn't break. In fact didn't know that functionality was there. 

My current plan is auto detection based on file extension. `zip` or `gz`. I'll start there and y'all can have a look when there is a PR.

**Comment by jtniehof** [comment]
Might be a bit out of scope for first implementation, but being able to read multiple files in a single zip would be nice, have it handled as if there were a list of filenames.

**Comment by balarsen** [comment]
> 
> 
> Might be a bit out of scope for first implementation, but being able to read multiple files in a single zip would be nice, have it handled as if there were a list of filenames.

That would be good, I agree a big chunk to bite off.

**Comment by balarsen** [comment]
We re going to need to test on zip and gzip data files. Preference?

1. Add a zip and gzip file to the repo in the `tests/data` directory
2. Generate the zip and gzip versions on the fly in the tests

I am leaning towards 2, and updating the tests a bit to allow for less repeated code. 

@jtniehof @drsteve

**Comment by jtniehof** [comment]
Agree on door number 2. Make a helper function that opens a filename passed in and does the test, and have three testXXX functions that call it with uncompressed, zip, gzip.

**Comment by balarsen** [comment]
Great, some variation on that started.
