### ISSUE TITLE
Migrate CI off Travis

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#455]
Travis migrated to a [new billing structure](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) back in November. As part of this change, we were put onto a plan with a fixed number of credits, nonrefilling. Those credits have now been used and our builds are not executing. A later post [claims commitment to Open Source](https://blog.travis-ci.com/oss-announcement) but with no further information. The original post states that open source projects will have to request credits on a case-by-case basis. [It appears those are no longer being considered](https://twitter.com/james_hilliard/status/1336081776691843072). Even before that, [reports are that requirements include nobody on the project getting paid](https://news.ycombinator.com/item?id=25338983).

I have disabled the requirement that CI pass to merge PRs; reviewers should build and run the unit tests (there's a developer/scripts/test_all.sh that can help with this on Linux). I have also suspended access by the Travis GitHub app.

Options that I see:

1. Pay for Travis. Cheapest plan I found was $70/mo.
2. Request Open Source credits, with the understanding we'll probably have to keep requesting them.
3. Stop using cloud-hosted and GitHub-integrated CI in favor of hand-run tests, e.g. by PR reviewers. Our CI doesn't get us Mac or Windows anyhow (Travis charges more for Mac now) so maybe a duct tape solution is the way.
4. Migrate to CircleCI. We're using it on dbprocessing and it's okay, although two months ago we went through a similar dance with DockerHub changing the terms of free access, which fortunately worked out okay.
5. Migrate to Jenkins, either self-hosted or finding a provider. Frankly option 3 might be easier.
6. Migrate to [GitHub Actions](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

My recommendation would be to try GitHub Actions with maybe a side of punching up our developer-hosted testing. This can allow for much more comprehensive testing and deal with cross-platform as well. And it puts us in a better position in case something similar happens with whatever CI we're using. If GitHub becomes intractable we're in trouble anyhow.

**Comment by jtniehof** [comment]
Also leaning towards getting 0.2.2 out the door with local testing before digging into this.

**Comment by jtniehof** [comment]
[Further discussion](https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/1)

**Comment by jtniehof** [comment]
There's a [GitHub action to simplify migration off Travis](https://github.com/marketplace/actions/run-travis-yml).

**Comment by balarsen** [comment]
I like GitHub actions unless you dbprocessing circleCI makes that really easy (doesn't sound like that).

**Comment by jtniehof** [comment]
I can probably do a cruddy CircleCI setup faster than a cruddy GitHub Actions setup, just from having some CircleCI experience. But that CircleCI experience was not "OMG this is the best thing ever!" and doing a good setup (e.g. trying to do some pip cacheing across builds) is going to be probably equally hard on each, maybe easier on GHA. I'm a little wary of this sort of thing happening again and just have a gut feeling that it's less likely GHA will pull the rug out from us than CircleCI. Not that I'm _expecting_ that from CircleCI.

**Comment by jtniehof** [comment]
I'm declaring this a blocker for 0.2.3.

**Comment by jtniehof** [comment]
As I close in on getting GHA working, I'm considering _also_ setting up CircleCI. If we have two functional CI systems then we won't get caught flat-footed if the terms change on us again. Once both are working we can not require the checks on one of them and cut it back to a minimal run.
