### ISSUE TITLE
Macports F2py not found by Setup.py

### ISSUE THREAD

**Issue by spacecataz** [spacepy/spacepy#456]
Setup.py does not find f2py installs via Macports when `port select` is used to set the default Python version (e.g., `python` softlinks to `python3.8`, etc.).
`sys.executable` reports the executable as "python" without a version number.  Because MacPorts installs f2py as f2py-(version) and no softlink is made via `port select`, `f2py` is not found as a valid executable in any of the search paths.

Ultimately, this is a MacPorts issue that has been reported over there.  However, MacPort devs are not willing to add a `select` entry for f2py.  Changing Setup.py to address this would be straight forward.

### Minimal example to reproduce issue:
After installing python and all dependencies via Macports...

```
which f2py
which f2py-3.8
port select --summary
echo "------------"
python setup.py build
```

### Error message/Traceback:

```
f2py not found
/opt/local/bin/f2py-3.8
Name                    Selected              Options
====                    ========              =======
ipython                 py38-ipython          py37-ipython py38-ipython none
ipython3                py38-ipython          py37-ipython py38-ipython none
pip                     pip38                 pip37 pip38 none
pip3                    pip38                 pip37 pip38 none
python                  python38              python27 python27-apple python36 python37 python38 none
python3                 python38              python36 python37 python38 none
sphinx                  py38-sphinx           py37-sphinx py38-sphinx none
------------
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running build_py
customize Gnu95FCompiler
Found executable /opt/local/bin/gfortran
Found executable /opt/local/bin/ar
Found executable /opt/local/bin/ranlib
error: [Errno 2] No such file or directory: 'f2py'
```

### OS, Python version, and dependency version information:

>>> print(platform.platform())
macOS-10.15.7-x86_64-i386-64bit
>>> print(sys.version_info)
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
>>> print('numpy={0}'.format(numpy.__version__))
numpy=1.19.1
>>> print('scipy={0}'.format(scipy.__version__))
scipy=1.5.2
>>> print('matplotlib={0}'.format(matplotlib.__version__))
matplotlib=3.3.0

### Version of SpacePy
Master branch pulled today.

**Comment by spacecataz** [comment]
I can fix this quick, but am not sure about the best way to proceed.  It looks like `platform` could get us enough information to work with:
```
import platform
platform.python_version_tuple()
```
There are a number of functions in `sys` that would do the trick, too, but I'm not sure what is most acceptable.

**Comment by jtniehof** [comment]
It looks like `sys.version_info` is probably preferred. What you probably want to do is edit `default_f2py` and append `-x.y` and `x.y` to `suffixes`. That way if the python interpreter has a suffix that will happen first, then then `f2py-x.y` that Macports seems to like, and finally `f2pyx.y` in case somebody else goes for that.

**Comment by jtniehof** [comment]
Also the check for interpdir should probably come after all the PATH checks (i.e. that if statement should be out-dented one level) while you're working on it....
