### ISSUE TITLE
pycdf:  VisibleDeprecationWarning: ndarray from ragged nested sequences

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#460]
'''
python3.8/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
'''

### Minimal example to reproduce issue:
```
python test_pycdf.py NoCDF.testHypersliceDimensions
```
### Error message/Traceback:
```
(python3) balarsen@pn2006943:~/git/spacepy/tests$ python test_pycdf.py NoCDF.testHypersliceDimensions
This unreleased version of SpacePy is not supported by the SpacePy team.
/home/balarsen/miniconda3/envs/python3/lib/python3.8/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
```

### OS, Python version, and dependency version information:
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.4
scipy=1.5.4
matplotlib=3.3.3
```

### Version of SpacePy
376539978a44189faf433695ae169f102edac9b2

**Comment by jtniehof** [comment]
This is an interesting one and I'm not sure exactly how to address it. The test is intentionally passing in a ragged array to make sure it's caught and the appropriate error raised. This used to just make an array of lists and that's how it's caught. I suppose the check could explicitly catch this warning, but it's a piece of code that gets called a LOT, so I don't want to mess it up. It would also be nice if we could find out what numpy is going to do with this sort of thing once the deprecation period is over; presumably it's going to raise some sort of error that we'll want to catch.

The good news is that this warning only comes up if you're doing something that's going to cause an exception anyhow.
