### ISSUE TITLE
spacepy.empiricals .getPlasmaPause prints a warning not raise/error

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#474]
`spacepy.empiricals.getPlasmaPause` prints a warning, should either raise a warning or raise a `ValueError`

See:

https://github.com/spacepy/spacepy/blob/a4c0ca6895dc2c419c9cd0a71d1d85b62f7f89db/spacepy/empiricals.py#L124

### Minimal example to reproduce issue:
import spacepy.time as spt
import spacepy.empiricals as emp
ticks = spt.tickrange('2002-01-01T12:00:00','2002-01-04T00:00:00',.25)
emp.getPlasmaPause(ticks, model='CA1992', LT=12)

### Error message/Traceback:
```
array([3.76      , 3.76      , 4.35799998, 4.35799998, 4.35799998,
       4.35799998, 4.35799998, 4.35799998, 4.35799998, 4.54200002,
       5.14      ])
```

### OS, Python version, and dependency version information:
```
Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.10
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
numpy=1.19.4
scipy=1.6.0
matplotlib=3.3.3
```

### Version of SpacePy
76c5a35c688e7876292ce05f3bf833a793d77fd6

**Comment by balarsen** [comment]
@drsteve preference on behavior? I like `ValueError`.

**Comment by jtniehof** [comment]
It looks like it should be a warning, not an error, because there are CA1992 parameters in the `else` of the `if LT=='all'. Maybe `RuntimeWarning`? Or should it just go in the documentation and not issue a warning?

**Comment by drsteve** [comment]
I'd be good with a `RuntimeWarning` here, as it's a valid model (and different models do allow explicit LT dependence).  Nobody reads documentation, so a warning seems appropriate. Warnings are also easier to squelch than a print.
