### ISSUE TITLE
Rename default branch of repository

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#476]
[git has decided](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) to move away from `master` as the default branch name as part of the broader reconsideration of terminology in tech and its possible negative implications. [github is providing some support](https://github.com/github/renaming/) for this and supposedly more tools are coming this month.

I suggest switching to `main` once those new github tools are available, since `main` seems to be what the community is settling on. We could also prioritize and make the switch sooner; see [existing documentation on changing the default branch](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch).

Assuming this plan is okay, I'll probably just pick an afternoon once GitHub says everything is in place and make the change then. There may be a PR with documentation if this doesn't wind up being nearly transparent.

**Comment by balarsen** [comment]
I wholeheartedly agree with the change. We should allow githut and other projects to work out how to make the transition as painless as possible.

**Comment by jtniehof** [comment]
Looks like github changes are in place to support this, so I'll look it over when I get some time.

**Comment by balarsen** [comment]
To capture it here: https://github.com/github/renaming
