### ISSUE TITLE
Transition offical repo from sourceforge to github

### ISSUE THREAD

**Issue by drsteve** [spacepy/spacepy#5]
@spacepy/core Team, @spacecataz 
### Please weigh in with your comments on this issue tracker.

I'm looking to change the status of this repo from our unofficial mirror to the official repo.

Pros
----
- We can set up continuous integration with Travis (on multiple versions of Python) so we actually see the test failures
- GitHub has better visibility and I'd like the official repo to be the one people find
- Zenodo has good github integration and our releases could be auto-archived and assigned DOIs so they are citeable
- We can use github pages to provide a new homepage, since the old one is defunct
- It looks like PyPI actually tracks stars and forks of github repos when the project URL points to GitHub, and I like that feature!

Cons
----
- One or more of the core developers would need greater permissions for this group[1]
- We'd want all the devs to switch to using the github.
- We'd need to work out what to do with the repo over at SourceForge[2]
- Are there really more cons?

I'd also like to then enable a 2 person review for each pull request and have everyone fork the repo and send pull requests when they have updates. That way test failures happen outside the master branch.

Finally, for this thread anyway, I'd like people to start thinking about what needs to go into issue trackers here. We have all sorts of gaps in documentation, there are outstanding items that probably don't have issue trackers, ... even if you're working on something, it probably warrants a tracker. We should also start tagging some of these as "beginner friendly" to encourage user participation. If it looks like we can sensibly change to using github as our primary then I'd like to do it ASAP. There's a paper on Python in Heliophysics in preparation and SpacePy is one of the packages under discussion. I'd like to be able to at least tag a current version and archive it at Zenodo before submission (estimated in less than 2 weeks) so the code can be properly cited.

Steve

[1]: @graingert Can you make all of the core team owners on the group? That'd be really helpful.
[2]: SourceForge isn't the pit of malware it used to be - it got bought out a couple years back and is legit again. So we probably can actually delete the project if we want to, or we can look at automated syncing.

**Comment by spacecataz** [comment]
Define greater permissions.  Would this make pushing/pulling etc. more of a pain in the ass for non-LANL folks?  Asking for a friend.

**Comment by drsteve** [comment]
@spacecataz Separate issues (mostly).
- Currently you aren't a member of this group so you'd need to fork the repo and commit/push to your fork. Then you'd need to send a pull request. Marginally more of a pain that directly committing to the repo, but we should be doing this anyway (and we are for other projects like RAM-SCB). It will be exactly as much a pain for you as everyone else.
- Greater permissions is in reference to the spacepy group. Currently Brian, Jon and myself are members, but not owners. That means we don't have permissions to, e.g., make new repos in the group, define new teams for communications purposes. If we're going to move the official here I want several of us to have full permissions, otherwise it's not happening.

@balarsen As far as I can tell the general consensus on the Microsoft buyout is that it's probably a good thing. Certainly the news about that has spread further than the news that SourceForge has new owners (happend a couple years ago) and isn't a hellpit any more. IMO GitHub is a better place to host the official than SourceForge.

**Comment by jnlanl** [comment]
I'd like to ditch SF and the long-defunct LANL page and switch to github + pythonhosted (or readthedocs.io).

**Comment by drsteve** [comment]
Reupping. Can @graingert help a fellow Southampton alumnus out by making the core team owners on the group? Thanks!

**Comment by drsteve** [comment]
And again... @graingert 
Can you please add at least one of the other core team members as owner on the spacepy group? If you add me I'll take it from there. Cheers.

**Comment by drsteve** [comment]
Still hoping for a reply from @graingert here. Can you please add one or more of the folks in this conversation as owners of the spacepy group? That way we'll be able to support a migration to GitHub of the official repo.

**Comment by graingert** [comment]
@drsteve invited you as an owner

**Comment by drsteve** [comment]
Great, thanks!

Let the migration begin! I'll close this tracker once we've completed the transition to this as the official repo. That includes migrating any bug or issue trackers that are still open and relevant. I'll look into automated syncing to the SF repo, or we can just kill it dead and leave a note saying where we are.

Please all fork the repo from here and do any further work on your own fork, then send pull requests. Ideally someone other than the originator would approve a merge request.

**Comment by jtniehof** [comment]
I changed permissions on sourceforge so now nobody has push permission. I will do a pull request for a final merge of sf.

How to pull requests and individual branche work with a rebase-oriented workflow? github normally does --no-ff and I've really gotten to like a rebase-oriented workflow to avoid the railroad tracks.

**Comment by graingert** [comment]
It just works: https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits

**Comment by drsteve** [comment]
Thanks @graingert

**Comment by balarsen** [comment]
Is this done?

**Comment by drsteve** [comment]
I think all that's left is migration of any outstanding trackers from SF to here. If you wanted to make a ticket for tracker migration (including closing trackers with an appropriate reason on SF) and close this then I'm good with that.

**Comment by drsteve** [comment]
All tickets at SF have been closed, and opening new tickets has been disabled. The banner says the project has migrated. I'm going to go ahead and close this so we don't have a stale issue here.
