### ISSUE TITLE
Failed to install spacepy on macOS

### ISSUE THREAD

**Issue by wyli1124** [spacepy/spacepy#521]
System: macOS Big Sur 11.1;
Method to install: https://spacepy.github.io/install_mac.html

I got a long list of errors when > pip install ffnet 
also when > pip install spacepy 

Here is the final part of the error message. Any help is appreciated. 

########### EXT COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: x64
      Compiler    : gcc

    CPU baseline  :
      Requested   : 'min'
      Enabled     : SSE SSE2 SSE3
      Flags       : -msse -msse2 -msse3
      Extra checks: none

    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Generated   : none
    CCompilerOpt._cache_write[796] : write cache to path -> /private/var/folders/ws/8kyhn_7s7655mfj_1dnj3pzm0000gn/T/pip-install-qiog2b_x/ffnet_7bab6dc2a15c49dab1dfc5e4d0567b36/build/temp.macosx-10.9-x86_64-3.8/ccompiler_opt_cache_ext.py
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/wyli/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ws/8kyhn_7s7655mfj_1dnj3pzm0000gn/T/pip-install-qiog2b_x/ffnet_7bab6dc2a15c49dab1dfc5e4d0567b36/setup.py'"'"'; __file__='"'"'/private/var/folders/ws/8kyhn_7s7655mfj_1dnj3pzm0000gn/T/pip-install-qiog2b_x/ffnet_7bab6dc2a15c49dab1dfc5e4d0567b36/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ws/8kyhn_7s7655mfj_1dnj3pzm0000gn/T/pip-record-q_7v1wyl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wyli/opt/anaconda3/include/python3.8/ffnet Check the logs for full command output.

**Comment by jtniehof** [comment]
With #603, the ffnet install issue in the logs is no longer relevant, so closing.
