### ISSUE TITLE
matplotlib 3.4 breaks spacepy.plot

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#525]
The CI is currently in the process of breaking because matplotlib 3.4 has the `plasma` colormap and no longer allows calling `register_cmap` if a colormap is defined. At least that's my guess; the 3.4 docs are not up on matplotlib's site, and `plasma` did exist in 2.1. `plot` should probably be updated to check if the colormap is registered and skip if it already is.

**Comment by drsteve** [comment]
Solution (assuming it actually is the solution) seems good to me. Just making a note here that when we bump our minimum matplotlib version to 2.0 we can drop that set of colormaps and just use the matplotlib built-ins. Currently I think our minimum is 1.5...

**Comment by jtniehof** [comment]
The new docs are up. [register_cmap](https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.register_cmap) now asks to pretty-please not override system names and won't do so without a kwarg that [didn't exist before](https://matplotlib.org/3.3.3/api/cm_api.html#matplotlib.cm.register_cmap). Colormap handling was also overhauled. Since SpacePy's should be the same as matplotlib's, I'm not inclined to force the override.

Also I'm not inclined to test this very deeply, since as you say we'll be dropping these in the not-too-distant future. (Selfishly, I'm trying to get systems off 16.04 and then would be happy to raise the minimum; I think this would count as "convoluted workaround.")
