### ISSUE TITLE
conda build

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#54]
Ultimately we want people to be able to do "conda install spacepy" and have it just work. Notes/comments here towards that.

**Comment by drsteve** [comment]
Commenting in part to bump this.

Questions:
- Where in the timeline were you thinking about this? My thought is (probably the same as yours) that this is post-0.1.7. That is, get an 0.1.7 release with a Windows installer and then do a conda build.
- Spacepy should have its own account on Anaconda Cloud for this, correct? How do we want to manage that?

**Comment by jtniehof** [comment]
This has changed so much since I last looked at it (binstar-era) that I have little idea on how to progress; there'd be some research.

I do think you touch on two things that are important: 1) timing of cleanup/excrement-shoveling activities. I put all the Windows release stuff in that category, docs rework, PEP-8, etc. We should schedule those to avoid burnout, and I'd consider anything release and installer related to be most important (those seem to be biggest pain points.) 2) control/accounts for the infrastructure. GH membership, pypi handling, travis, anaconda cloud. We should probably try to have a consistent story for handling them. Right now I think I? have the PyPI account and you have the Travis account and that should probably be spread around.

**Comment by Juanlu001** [comment]
We almost foue years ago without success https://github.com/conda-forge/staged-recipes/pull/1781. With a bit of support from spacepy devs we could try again. The main pain point is compiling cdflib. Thoughts? @AlexS12

**Comment by Juanlu001** [comment]
_Edit: Typos_

**Comment by AlexS12** [comment]
I am trying with this one currently https://github.com/conda-forge/staged-recipes/pull/10847/files

**Comment by jtniehof** [comment]
Thanks for chipping in on this!. Let's try to coordinate through this issue. It's going to take me a little bit to come up to speed and I want to make sure that the conda builds are part of our normal release process.

cdflib is a non-issue in this context because SpacePy doesn't use it. pycdf wraps the main NASA CDF library, and having a conda build of SpacePy would still be useful even if the user has to grab the NASA library. (We're working on having SpacePy do the grab on request, anyhow.)

**Comment by Juanlu001** [comment]
> We're working on having SpacePy do the grab on request, anyhow.

Just FYI, another library I ported to conda-forge, SpiceyPy, does a similar thing, and we had to apply [some](https://github.com/conda-forge/spiceypy-feedstock/blob/master/recipe/0001-simpler-patch-for-conda-forge-dist.patch) [patches](https://github.com/conda-forge/spiceypy-feedstock/blob/master/recipe/0002-Get-rid-of-setup_requires.patch) for it to work.

In the context of conda, the best approach would be to (1) have a `conda install nasa-cdflib -c conda-forge` and (2) have `conda install spacepy -c conda-forge`, depending on `nasa-cdflib`.

**Comment by jtniehof** [comment]
The plan isn't to grab the library on install, but on user request post install. Ideally, yes, having conda support for the actual CDF library would be great, but not necessary.

**Comment by johncoxon** [comment]
I'm very keen to see this happen as I use conda environments more and more – has there been any work on this lately?

**Comment by edmundhenley-mo** [comment]
@johncoxon - in case useful as a workaround, and in case you weren't aware, note you can have a pip install of spacepy within a conda .yml file. 
See for example [here](https://github.com/HarveySouth/spaceapps-2022/commit/976f7675d80c679693ce79cd3f84492a6dae2d58#diff-56acef28455cc72c85a8c51f919c84319325400bea23f6b83e580b91717f1068R21-R23), used in a recent NASA SpaceApps hackathon.
This isn't perfect for all use-cases - installing this way doesn't let you expose the dependency via a conda lock file for a perfectly reproducible environment. And AFAICR we had some solve issues later when adding some extra packages - solver seemed to struggle a bit across pip and conda. But might still be useful for some use-cases.

**Comment by johncoxon** [comment]
Thanks! This is useful.

**Comment by jtniehof** [comment]
This is still very much on the radar, but it's going to have to follow other installer updates, specifically moving to pure-setuptools installer and then getting binary wheels across all platforms. Those changes are in progress.

**Comment by jtniehof** [comment]
Closing as a duplicate of #678. This may sound ridiculous, but parts of this discussion are somewhat out of date and it's probably better to have a clear start point under the current conda-forge environment.
