### ISSUE TITLE
pycdf can't see CDF library on M1 mac

### ISSUE THREAD

**Issue by johncoxon** [spacepy/spacepy#544]
My issue is that I can't import the `pycdf` submodule.

### Minimal example to reproduce issue:
I installed spacepy by cloning the repo to get around issue #530, checking out the 0.2.2 release tag, and running `python setup.py install`. Then I ran `from spacepy import pycdf` and I get an error as described below. Running `os.environ[CDF_LIB]` returns `/opt/cdf/cdf/lib` which is the location of the CDF library on my machine, as expected.

### Error message/Traceback:
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-a80d87add280> in <module>
----> 1 from spacepy import pycdf

/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/spacepy/pycdf/__init__.py in <module>
   1284 _libpath, _library = Library._find_lib()
   1285 if _library is None:
-> 1286     raise Exception(('Cannot load CDF C library; checked {0}. '
   1287                      'Try \'os.environ["CDF_LIB"] = library_directory\' '
   1288                      'before import.').format(', '.join(_libpath)))

Exception: Cannot load CDF C library; checked /opt/cdf/cdf/lib/libcdf.dylib, /opt/cdf/cdf/lib/libcdf.dylib, /opt/cdf/cdf/lib/libcdf.dylib. Try 'os.environ["CDF_LIB"] = library_directory' before import.
```

### OS, Python version, and dependency version information:
```
macOS-11.5.2-arm64-arm-64bit
sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)
numpy=1.21.2
scipy=1.7.0
matplotlib=3.4.3
```

### Version of SpacePy
I cloned the repo, and checked out release 0.2.2 on the `master` branch.

**Comment by jtniehof** [comment]
Thanks for the details. I see you're on an ARM Mac. Was the CDF library compiled for the same architecture as your Python? (Either ARM or Intel under Rosetta). If those don't match, it won't be able to load.

Incidentally if you're grabbing a release you don't need to clone and check out the tag; there are [downloads available for the releases](https://github.com/spacepy/spacepy/releases).

**Comment by johncoxon** [comment]
Hello! I believe so, as the CDF installer on the NASA website says it's universal and so I assume it installed the correct versions for my architecture, but is there a way to check with the terminal? I used `https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf38_0/macosx/cdf38_0_1-setup_universal_binary.tar.gz`.

Thanks for the tip on the release downloads, I should've looked there first.

**Comment by jtniehof** [comment]
I'm shooting in the dark here a bit, since I just got my hands on an Intel Mac and don't have an M1, but you can try running `file` on both the CDF library (the dylibs listed in the error message) and the python interpreter (`which python`, which should be in your miniforge environments). You can also post what other files are in `/opt/cdf/cdf/lib/` and we can see what looks suspicious.

I'm highly skeptical that the CDF release is a universal ARM/x86_64 library, because it's dated August of 2020 and the M1 Macs weren't announced until November of 2020 (although the silicon was announced in June). Because it still supports OSX 10.3, my guess is it's more likely a PPC/x86 universal, or maybe 32/64.

Just to show what this looks like, although on a Linux system:
```
# this has to be run on the actual library file, other files might be a symlink....
$ file libcdf.3.8.0.so 
libcdf.3.8.0.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=262888c6218a0000a02a3b14e393ff1e7e9a8b21, not stripped

$ which python3.6
/usr/bin/python3.6
$ file /usr/bin/python3.6
/usr/bin/python3.6: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=543ad88cf3d474885741b21d10975f11c63b4f04, stripped
```

**Comment by johncoxon** [comment]
Your suspicions were right – the "universal" refers to still supporting PPC rather than newly supporting ARM, which is frustrating. That almost certainly explains why it's struggling. I've tried to compile the CDF libraries from scratch but I hit the same error on my Intel Mac and my ARM Mac so I think there's a problem with the makefile – I have emailed the CDF team to ask for help there. Thanks!

**Comment by jtniehof** [comment]
Hope you don't mind me reopening this. I'd like to figure out a way forward, even if it's just documenting how to use Rosetta and an x86 Python install in the meantime, or compiling the CDF library yourself. @spacecataz was going to take a look at this on his M1 and see if he can figure something out.

**Comment by johncoxon** [comment]
No problem at all! I didn't want it to clutter things for you if it was an issue with another library, but very glad to have you all working on it, thank you!

**Comment by johncoxon** [comment]
Hi @jtniehof, I was just wondering if you had any idea what the likely timeline is on this? I gather it's turned out more complex than originally thought?

**Comment by jtniehof** [comment]
I imagined it was fairly complex, but I also envisioned @spacecataz and I might actually get some time at the same time sooner than all this--since I don't have an M1 mac it's a bit of a weird arms-length kind of thing we have to do. This is absolutely on our radar and I'm hoping we can carve out the time soon.

**Comment by jtniehof** [comment]
The latest NASA CDF library (3.8.1) is a universal x86/arm64 binary. As of SpacePy 0.4.0, the pycdf functionality works (#614), and #649 addresses the last details of installing on Apple Silicon. So I'm going to call this closed.
