### ISSUE TITLE
irbempy.get_Lstar raises error if multiple cpu's are used

### ISSUE THREAD

**Issue by wutzig** [spacepy/spacepy#549]
My issue is ...
In `irbempy.py` the function `get_Lstar` calls its own private function `get_ov` if multiple cpu's are being used.
Within `get_ov(fullov, stind, enind)` an error is raised at
* `dum = keylist.pop(keylist.index('Qbits'))`
if `fullov` does not contain key `Qbits`
replace line with `keylist.pop('Qbits', None)`

* `out['Qbits'][key] = fullov['Qbits'][key][stind:enind]`
if `fullov` does contain `Qbits` as a non-empty dictionary
before this line insert `out['Qbits'] = dict()`

### Minimal example to reproduce issue:

```
from spacepy import time, coordinates, omni, irbempy
from datetime import datetime
num_points = 1000
coords = coordinates.Coords([[6.6, 0, 0] for _ in range(num_points)], 'GSM', 'car')
time_ticks = time.Ticktock([datetime(2008, 3, 20) for _ in range(num_points)])
omnivals = omni.get_omni(ticks=time_ticks)
Lstar = irbempy.get_Lstar(
    ticks = time_ticks,
    loci = coords,
    extMag = 'T89',
    omnivals = omnivals
)
```

### Error message/Traceback:

```
Traceback (most recent call last):
  File "/export/spacepager2/PAGER/wutzig/pager/verb4d_py/main.py", line 10, in <module>
    tracker.execute()
  File "/export/spacepager2/PAGER/wutzig/pager/verb4d_py/Verb4DSimulation/Verb4DSimulation.py", line 76, in execute
    if self.update_dict['create_LEA_J']: self.create_LEA_J()
  File "/export/spacepager2/PAGER/wutzig/pager/verb4d_py/Verb4DSimulation/core/_create_LEA_J.py", line 53, in create_LEA_J
    Lstar = get_Lstar(
  File "/export/spacepager2/PAGER/wutzig/miniconda3/lib/python3.9/site-packages/spacepy/irbempy/irbempy.py", line 1721, in get_Lstar
    ov.append(get_ov(omnivals, startind, endind))
  File "/export/spacepager2/PAGER/wutzig/miniconda3/lib/python3.9/site-packages/spacepy/irbempy/irbempy.py", line 1663, in get_ov
    out['Qbits'][key] = fullov['Qbits'][key][stind:enind]
  File "/export/spacepager2/PAGER/wutzig/miniconda3/lib/python3.9/site-packages/spacepy/datamodel.py", line 484, in __getitem__
    raise(KeyError('{0}'.format(key)))
KeyError: 'Qbits'
```

### OS, Python version, and dependency version information:

Linux-5.11.0-34-generic-x86_64-with-glibc2.31
sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
numpy=1.20.2
scipy=1.6.2
matplotlib=3.4.2

### Version of SpacePy

0.2.2
GitHub pull

**Comment by drsteve** [comment]
Thanks for the report. I can reproduce and have a fairly clean fix in mind, but this can also be worked around pretty easily.
It's not actually necessary to provide the "omnivals" data. If it's omitted then each process will independently look up the required data.

Try the following:
```
from spacepy import time, coordinates, omni, irbempy
from datetime import datetime
num_points = 1000
coords = coordinates.Coords([[6.6, 0, 0] for _ in range(num_points)], 'GSM', 'car')
time_ticks = time.Ticktock([datetime(2008, 3, 20) for _ in range(num_points)])
Lstar = irbempy.get_Lstar(ticks=time_ticks, loci=coords, extMag='T89', omnivals=None)
```
This does still look up the Kp values required for the Lstar evaluation, but it's doing it in the `prep_irbem` call that's done per pool worker (which works just fine). For reference, `omnivals=None` is the default argument here, so you can just omit and it'll do the same.

Obviously the handling of the data in the multi-process wrapper is not doing this correctly, so I'll put this on my to do list to fix. In the interim, unless you're pulling your data from a non-SpacePy source then I'd suggest just omitting the step of explicitly looking up the "omni" data.

**Comment by wutzig** [comment]
Thanks for looking into that. As we're using irbempy for forecasting we provide our own Kp predictions rather than using omniweb.

**Comment by drsteve** [comment]
The draft pull request #551 should fix your problems. I'll figure out adding tests for our continuous integration when I next get a moment. Can you pull the PR and check that it works for you?
