### ISSUE TITLE
ffnet error

### ISSUE THREAD

**Issue by hmkim-aurora** [spacepy/spacepy#572]
There are long lines of error messages when installing SpacePy (pip install --upgrade spacepy) on my new Mac (M1, OS 12 Monterey).

I installed Anaconda so everything is fresh installed. In the middle of the messages, the following seems to be the main one:

  CCompilerOpt.cc_test_flags[1003] : testing failed

  CCompilerOpt.dist_test[576] : CCompilerOpt._dist_test_spawn[711] : Command (clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/hyominkim/opt/anaconda3/include -arch x86_64 -I/Users/hyominkim/opt/anaconda3/include -fPIC -O2 -isystem /Users/hyominkim/opt/anaconda3/include -arch x86_64 -I/Users/hyominkim/opt/anaconda3/include/python3.9 -c /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c -o /var/folders/tx/vdr71c196vq4jvqgpsm3wpxr0000gn/T/tmph0at3c6n/Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.o -MMD -MF /var/folders/tx/vdr71c196vq4jvqgpsm3wpxr0000gn/T/tmph0at3c6n/Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.o.d -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512er -mavx512pf -Werror) failed with exit status 1 output ->

  /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:9:9: error: implicit declaration of function '_mm512_4fmadd_ps' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

      b = _mm512_4fmadd_ps(b, b, b, b, b, NULL);

          ^

  /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:9:9: note: did you mean '_mm512_fmadd_ps'?

  /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/avx512fintrin.h:2716:1: note: '_mm512_fmadd_ps' declared here

  _mm512_fmadd_ps(__m512 __A, __m512 __B, __m512 __C)

  ^

  /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:9:7: error: assigning to '__m512' (vector of 16 'float' values) from incompatible type 'int'

      b = _mm512_4fmadd_ps(b, b, b, b, b, NULL);

        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:11:9: error: implicit declaration of function '_mm512_4dpwssd_epi32' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

      a = _mm512_4dpwssd_epi32(a, a, a, a, a, NULL);

          ^

  /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:11:9: note: did you mean '_mm512_dpwssd_epi32'?

  /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/avx512vnniintrin.h:68:1: note: '_mm512_dpwssd_epi32' declared here

  _mm512_dpwssd_epi32(__m512i __S, __m512i __A, __m512i __B)

  ^

  /Users/hyominkim/opt/anaconda3/lib/python3.9/site-packages/numpy/distutils/checks/cpu_avx512_knm.c:11:7: error: assigning to '__m512i' (vector of 8 'long long' values) from incompatible type 'int'

      a = _mm512_4dpwssd_epi32(a, a, a, a, a, NULL);

        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  4 errors generated.

  

  CCompilerOpt.feature_test[1458] : testing failed

As well as these lines,

    ld: library not found for -lSystem

    collect2: error: ld returned 1 exit status

    error: Command "/Users/hyominkim/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/ffnet/fortran/_ffnetmodule.o build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/ffnet/fortran/fortranobject.o build/temp.macosx-10.9-x86_64-3.9/ffnet/fortran/ffnet.o build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/ffnet/fortran/_ffnet-f2pywrappers.o -L/Users/hyominkim/opt/anaconda3/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.5 -L/Users/hyominkim/opt/anaconda3/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/../../.. -L/Users/hyominkim/opt/anaconda3/bin/../lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/../../.. -lgfortran -o build/lib.macosx-10.9-x86_64-3.9/ffnet/fortran/_ffnet.cpython-39-darwin.so" failed with exit status 1

**Comment by jtniehof** [comment]
@spacecataz is our M1 person so he's probably best suited to help, but in the meantime it would help to isolate this between numpy, ffnet, or SpacePy. So try making sure numpy installs cleanly first:
`pip install numpy`
If that works, try ffnet:
`pip install ffnet`
If that doesn't work and [you aren't using LANLstar](https://spacepy.github.io/dependencies.html#soft-dependency-summary), then it's best to try installing SpacePy without dependencies, to isolate the SpacePy install:
`pip install --no-deps spacepy`

If that works, then bringing in the rest of the dependencies, without ffnet, will finish the job:
`pip install scipy matplotlib h5py`
