### ISSUE TITLE
Support UTF-8 in pycdf CHAR/UCHAR values

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#586]
NASA CDF C library 3.8.1 adds support for UTF-8 in variable records and Entries of type CDF_CHAR/CDF_UCHAR. This is primarily in the tools, not in the base library. Names (of attributes and variables) must still be in ASCII.

With raw variables, pycdf does no translation between bytes and strings. With "normal" variables and Python 3, the bytes are decoded to strings. This currently assumes ASCII, and failure raises a UnicodeDecodeError.

Proposed changes are:

- Set the default encoding to utf-8 instead of ascii, based on the assumption that people will now start making CDFs with UTF-8. This will not be CDF library dependent (a user still may have, say, 3.7, and there's no reason not to open newer files).
- Instead of raising an exception on failure to decode, use the "replacement" strategy, which puts Unicode fffd "Replacement Character" in the string (usually renders as a funky question mark).
- EDIT: Replaced with next option ~~Provide an "encoding" argument to the CDF constructor, to be used on both read and write. I don't _like_ doing this on write, it's more important people be able to read files in other encodings (e.g. I think Arase has some), but probably best for symmetry. Note that bytes (vs. strings) will still be written without any change. So it would be possible for "encoding" to only apply on read and assume, when writing, that everything should go UTF-8, and if the user doesn't like that they can encode the bytes themselves: `cdf.attr['Entry'][0] = entry.encode('shift-jis')`~~
- EDIT: Provide an "encoding" argument to the CDF constructor, to be used on both read and write. This allows people to read files in other encodings (e.g. I think Arase has some) and will maintain symmetry between read and write. However, as soon as a CDF is open read-write, and the encoding is not UTF-8, issue a warning of using a nonstandard encoding, but still use that encoding on writes. If the user wants to use a different encoding on write than on read, bytes are still written without change. So they can encode the bytes themselves: `cdf.attr['Entry'][0] = entry.encode('shift-jis')`. Warning is issued when switch to read-write, not on every write.
- EDIT: Continue to raise UnicodeEncodeError on _write_ if a unicode (str) value is passed in which cannot be encoded in the file's encoding. However, do not check if bytes are passed (i.e. do not try to encode the bytes just to make sure they're valid, if you pass bytes, they go directly).

**Comment by drsteve** [comment]
I think I like the edit, but can we make it a bit more unambiguous? (Or just confirm that my reading comprehension is flaky but still tolerable right now). 
 "still use that encoding on writes" means use whatever encoding is set at the file level? And the file-level encoding defaults to UTF-8?

So if someone reads, say, an Arase file and specifies 'shift-jis' encoding, then any modification will maintain that encoding? Unless the entry is manually encoded, in which case mix and match is cool?

Also, should we warn on character replacement (in the case of failure to decode)?

**Comment by jtniehof** [comment]
Your reading comprehension is indeed flaky but tolerable: encoding is utf-8 unless specified, if user specifies encoding, it is used for both reading strings from and writing strings to that file. But bytes get passed through in whatever encoding. (I am leaving Python 2 out of this, because I'm putting zero work into that....I don't even remember what I do if Unicode comes in on Python 2. It may all be the same codepath, in which csae it will work.)

Warning on character replacement would mean finding every decode and doing a search of the string for the replacement character. It would be a fair bit of code and probably some serious performance disadvantage.

**Comment by drsteve** [comment]
I was looking for some way to notify the user that the file didn't use UTF-8... So, for example, try to decode and on exception issue a warning and decode with replacement. I don't think we'd need to go as far as parsing the string to figure out what got replaced, just saying something didn't decode correctly would do, but it feels weird to have it silently replace characters.

I suppose the silent replacement is CDF's default position here, so maybe we can justify it.

**Comment by jtniehof** [comment]
The only way we know that there was a replacement is to either catch the exception (which means every single decode needs to be wrapped) or allow replacement and then search the string for the replacement character.

**Comment by drsteve** [comment]
I was thinking that the try/except should be fairly lightweight, but you're right that it would need to hit a lot of lines of code. All that just to provide limited value over CDF's stated position. Perhaps a note in the documentation on how to check for a replacement character would cover it.

**Comment by jtniehof** [comment]
#555 is related. I'm guessing doing this right will close that.

**Comment by jtniehof** [comment]
Just a note of edit to the original post: will continue to raise EncodeError when writing, but will not check if handed raw bytes to write.

**Comment by jtniehof** [comment]
Note to be sure to check cases where number of elements (bytes) does not match number of characters.
