### ISSUE TITLE
pybats testReadZip failure

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#59]
Windows, Python2, 32-bit. Fails in readascii, line 191, gzip.open...the resulting mode is rtb, so ValueError: InvalidMode ('rtb')

**Comment by jtniehof** [comment]
Same failure mode in ae9ap9Tests.test_readFileGzip

**Comment by jtniehof** [comment]
Both work in Python 3.6, 32-bit Windows.

**Comment by drsteve** [comment]
See https://bugs.python.org/issue30012 for an explanation (sort of) of what this almost certainly is.

It seems to me that the cleaner solution is to use the gzip default mode of opening as binary and use io.TextIOWrapper to handle to decoding, although the docs there suggest that this can be slow. Thoughts?

**Comment by drsteve** [comment]
Closed by #121
