### ISSUE TITLE
Crash in test_pycdf

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#60]
Python 2.7, 32-bit Windows, in the middle of test_pycdf crashes with a popup "python.exe has stopped working". `python test_pycdf.py NoCDF` fails. Running with any one test (e.g. `python test_pycdf.py NoCDF.testTypeGuessing`) does not fail. Running `python test_pycdf.py --verbose NoCDF` and it ends with:
```
testTypeGuessing (__main__.NoCDF)
Guess CDF types based on input data ...
```

so looks like the crash is in there but is preconditioned by some other test. They appear to be running alphabetically and TT2000ToEpoch16 is the one right before.

**Comment by jtniehof** [comment]
Works in Python 3.6, 32-bit Windows.

**Comment by jtniehof** [comment]
Simply running:
`python test_pycdf.py NoCDF.testTT2000ToEpoch16 NoCDF.testTypeGuessing`
is enough to reproduce the crash. Commenting out all the actual pycdf calls in testTypeGuessing, and just printing the test inputs in the main test loop (print(s)), it crashes on printing [1.0] (prints just the opening [, which might just be a question of when the output buffer gets flushed, but the next line is a stdout flush, so the statement clearly does not complete.) If I just print all the sample inputs (print(samples) before starting the main loop), crashes on the same print.

So it looks like the TT2000ToEpoch16 smashes that sample data somehow.

**Comment by jtniehof** [comment]
testTT2000ToEpoch16 has a single vectorized call to v_tt2000_to_epoch16, and then a loop of calls to tt2000_to_epoch16. Commenting out *either* the vectorized call *or* the loop of calls makes the problem go away (as does commenting out both.) If I comment out the loop but call the vectorized version 100 times, testTypeGuessing still fails (and on earlier sample data, with obvious corruption.) Calling the tt2000_to_epoch_16 loop in a loop 100 times makes it fail _in that loop_ (not even getting to testTypeGuessing), and I can get a failure with just `python test_pycdf.py NoCDF.testTT2000ToEpoch16`.

So the problem is definitely in TT2000 to Epoch16 and I can add a test that specifically does this tight loop and crashes itself.

**Comment by jtniehof** [comment]
This is getting brutal. If I make tt2000_to_epoch16 return 0., 0., it works; if I then have the function print the values, it crashes. If I print the two values in two separate print statements, it works; if I print them with the same print statement, it crashes.

**Comment by jtniehof** [comment]
Printing a list instead of a tuple works. So guess: there's something weird going on where the underlying ctypes c_double object is getting garbage collected at an inopportune time.

**Comment by balarsen** [comment]
Not likely the issue but a thing that could be cleaned up:
The line in     `def tt2000_to_epoch16(self, tt2000):`
       [` epoch16 = numpy.empty((2,), dtype=numpy.float64)`](https://github.com/spacepy/spacepy/blob/7d9d0522a498b2257e45d7d0448047b4c2025208/spacepy/pycdf/__init__.py#L1129 )

Should likely be a require as it is passed through to ctypes, maybe windows is not nice about contiguous etc.

**Comment by jtniehof** [comment]
Found it! It's a CDF library documentation bug: it claims it doesn't return anything, but actually returns a double, so that was being left on the stack and screwing things up.

@balarsen : Yeah, that was the first point of suspicion for me, as I was using ctypes arrays not numpy arrays on everything else...I'll be changing it to a ctypes array.

**Comment by balarsen** [comment]
Why did this only kill windows? Larger stack or different handling in OSX/Linux?

**Comment by jtniehof** [comment]
It's really specific; only Windows, 32-bit Python, Python 2.7. It probably just happened to go fandangoing on some part of the interpreter we actually used in that particular case.
