### ISSUE TITLE
Error, cannot import irbempylib

### ISSUE THREAD

**Issue by darrendezeeuw** [spacepy/spacepy#609]
My issue is that spacepy crashes due to a missing library, irbempylib. The compile and install complete without any error or warnings. This used to work and a month or two ago, but I updated my environment and not it's failing.

This is running on a Mac (Big Sur) and inside a conda environment. I even created a new environment from scratch with the same error.

### Minimal example to reproduce issue:

In [1]: from spacepy.coordinates import Coords
   ...: c1=[1,2,3]
   ...: sat_track = [[c1[i], c1[i], c1[i] ] for i in range(len(c1))]
   ...: cvals = Coords(sat_track, 'GEO', 'sph')
/Users/ddezeeuw/opt/miniconda3/envs/K522/lib/python3.7/site-packages/spacepy/time.py:2365: UserWarning: Leapseconds may be out of date. Use spacepy.toolbox.update(leapsecs=True)
  warnings.warn('Leapseconds may be out of date.'
/Users/ddezeeuw/opt/miniconda3/envs/K522/lib/python3.7/site-packages/spacepy/coordinates.py:242: DeprecationWarning: No coordinate backend specified; using IRBEM. This default will change in the future.
  DeprecationWarning)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-232bf6efde55> in <module>
      2 c1=[1,2,3]
      3 sat_track = [[c1[i], c1[i], c1[i] ] for i in range(len(c1))]
----> 4 cvals = Coords(sat_track, 'GEO', 'sph')

~/opt/miniconda3/envs/K522/lib/python3.7/site-packages/spacepy/coordinates.py in __init__(self, data, dtype, carsph, units, ticks, use_irbem)
    242                           DeprecationWarning)
    243         if use_irbem:
--> 244             from . import irbempy as op
    245         self.use_irbem = use_irbem
    246         # setup units

~/opt/miniconda3/envs/K522/lib/python3.7/site-packages/spacepy/irbempy/__init__.py in <module>
     69 
     70 
---> 71 from .irbempy import *
     72 

~/opt/miniconda3/envs/K522/lib/python3.7/site-packages/spacepy/irbempy/irbempy.py in <module>
     29 import spacepy.coordinates as spc
     30 import spacepy.datamodel as dm
---> 31 from . import irbempylib as oplib
     32 import spacepy.toolbox as tb
     33 

ImportError: cannot import name 'irbempylib' from 'spacepy.irbempy' (/Users/ddezeeuw/opt/miniconda3/envs/K522/lib/python3.7/site-packages/spacepy/irbempy/__init__.py)

### OS, Python version, and dependency version information:

In [1]: import platform
   ...: import sys
   ...: import numpy
   ...: import scipy
   ...: import matplotlib
   ...: 
   ...: print(platform.platform())
   ...: print(sys.version_info)
   ...: print('numpy={0}'.format(numpy.__version__))
   ...: print('scipy={0}'.format(scipy.__version__))
   ...: print('matplotlib={0}'.format(matplotlib.__version__))
   ...: 
Darwin-20.6.0-x86_64-i386-64bit
sys.version_info(major=3, minor=7, micro=13, releaselevel='final', serial=0)
numpy=1.21.5
scipy=1.7.3
matplotlib=3.5.2

### Version of SpacePy

python -m pip install --upgrade spacepy
This command used spacepy-0.3.0-cp37-cp37m-macosx_10_9_x86_64.whl

Also tried
https://files.pythonhosted.org/packages/8c/00/93d255f5ee22eb25c51a751909c552095ecbe37927eda86e8fcf2e218621/spacepy-0.3.0.zip

Also tried 
pip install --upgrade git+https://github.com/spacepy/spacepy.git
for cutting edge version.

**Comment by jtniehof** [comment]
This probably means irbem didn't compile and we'd need to see the output from the compliation to diagnose further. If you don't have a Fortran compiler installed, that's going to do it right off. Potentially related discussions/issues with things to try: #591, #585, #583. Remember that pip, by default, will not recompile, so you'll probably want to clean the pip cache when trying things out.

If all you need are coordinate transforms (and not B field, L*, etc.) you could [use the Python back end.](https://spacepy.github.io/coordinates.html)

**Comment by darrendezeeuw** [comment]
It worked for months then just stopped working, but I've been able to use the python back end and eliminate the need for irbem completely. My code works again. Thanks.

**Comment by jtniehof** [comment]
0.4.0 has lots of improvements relating to this, particularly in #639. Any new/persistent issues are probably going to be fairly different, so closing this issue.
