### ISSUE TITLE
pip builds against different numpy than installed.

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#638]
From #604 

On install, pip installs numpy in a separate environment to do the build. That can be a newer version of numpy (1.23, in my test case) than conda has installed (1.21), so the built module won't import in that environment. This will manifest as a warning of a numpy API mismatch, followed by a failure to import numpy.core.multiarray. Note 1.21 is API version 0x0e and 1.23 is API version 0x10.

This will only happen when installing with pip instead of setup.py, so there's a workaround. Another is to explicitly do pip install numpy before installing spacepy, which is of course a pain.

If I remove the numpy requirement from pyproject.toml, the build fails because pip is still using an isolated environment. Same if I have an empty pyproject.toml. Completely removing pyproject.toml fixes the problem, but that's not going to work with the migration to the New Way Of Installing Things.

Bottom line: pip makes no attempt to check if the version used to build a package is the same version that it will be installed under, even though it does check that the requirement exists.

I don't think this is Mac specific, it's just a question of what's available in conda vs. pip on any particular platform.

**Comment by jtniehof** [comment]
We've probably been seeing this more commonly on Mac because on Linux I expect less of this sort of mismatch to happen, and on Windows we're shipping binary builds--intentionally against a very old numpy to avoid this problem.

Two possible paths:

- Somehow instruct pip to build against the version of numpy in the install environment
- Instruct pip to build against the oldest possible numpy. I don't LIKE this because it reduces the source distribution to basically the level of the binary wheels, but it would probably work.

**Comment by jtniehof** [comment]
See pypa/pip#9542 , which seems to be a variant of "you're holding it wrong."

**Comment by jtniehof** [comment]
Ultimately I think this is coming down to the winds shifting against source distributions, and thus if installing from source, the first step is to build a binary distribution essentially exactly as it would be distributed for the world. There basically isn't a "nice" way to get a download/install from source that's machine specific.

Options:

1. Remove the requirement altogether and make the user install numpy first if installing from source. This isn't going to work long term, as just having the PEP517/518 structure triggers this issue.
2. Document using `--no-build-isolation`, either as a workaround or preferred means of installing from source. This *still* doesn't really do the job, because the build requirements are ignored as soon as you disable build isolation.
3. Use the [oldest-supported-numpy](https://pypi.org/project/oldest-supported-numpy/) metapackage, which install the oldest available numpy _that has a binary wheel_. This means the actual version used may not be static in time.
4. Manually specify a specific numpy version for every version of python in our build requirements. This is not as bad as it sounds, because we're already doing the work for specifying numpy versions in our CI and the wheel build scripts.

I vote 4, because it brings our build-from-source setup and our build-wheels-for-distribution setup closer to each other, which seems to be the way the wind is blowing anyway, and it means we aren't depending on a screwy metapackage. We can also document `--no-build-isolation`.

**Comment by drsteve** [comment]
So if I follow this right, using the `oldest-supported-numpy` would only use an older version _at build time_. An I wrong about that? Because if the ABI is forward compatible (as claimed) then we shouldn't care that the build time version is older and it won't affect whatever is used at runtime. If that's true, I suggest option 3.

If I've misconstrued things then I guess option 4...

**Comment by jtniehof** [comment]
Both options 3 and 4 only affect build time, the difference is whether we manage the build versions (4) or outsource it to someone else (3), in which case the build version may suddenly change out underneath us.

Our CI currently installs with `setup.py`, so it shouldn't be affected. If we add a `pip` test to the CI (probably a good idea at some point), it might build with a newer version of numpy than we test with--there definitely are some of the old versions which don't have binary wheels.

In either case (3 or 4), `pip` installs without an internet connection are basically going to require `--no-build-isolation`, as even if you have numpy installed it'll go grab another one. So this definitely needs to be documented. Case 3 just means it has to install two packages (the `oldest-supported-numpy` and numpy itself).

I think we're going to go for 4 and accept the "more work for more control" tradeoff at this point.
