### ISSUE TITLE
Test failure: test_toolbox.TBTimeFunctionTests.test_eventTimer

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#65]
Fails on the "result in" 0.25 or 0.26, line 752
Fails: 32-bit Windows, Python 3.6;  64-bit Windows, Python 2.7; 64-bit Windows, Python 3.6
Succeeds: 32-bit Windows, Python 2.7

**Comment by drsteve** [comment]
Using a Windows build as described in my comment on #67 I get no test failures in `test_toolbox.py`.
So for me, this all passes under 64 bit windows, Python 3.7.

**Comment by drsteve** [comment]
Can we confirm this is still a failure under the listed configurations?
I still don't see it on Windows under Python 3.7 (32-bit). And after removing my old Anaconda, installing 64-bit Miniconda, and setting up all the build environments using the script in `developers`...

- No failure in py3_64 environment (Python 3.6, 64-bit)
- No failure in py2_64 environment (Python 2.7, 64-bit)
- No failure in py3_32 environment (Python 3.6, 32-bit)

Can we confirm that this issue can be closed?

**Comment by jtniehof** [comment]
Failing in Python 2.7 32-bit for me now, which was the only one that succeeded. IMO the decimal=1 is way too loose. The issue may not be Windows but running a VM.

I'll work a quick PR to tighten up the timing a bit and loosen up the string match.

I'd definitely consider this a test failure not a code failure.
