### ISSUE TITLE
spacepy.toolbox.update() not working — host(s) of OMNI data down

### ISSUE THREAD

**Issue by asher-m** [spacepy/spacepy#663]
```
import spacepy.toolbox
spacepy.toolbox.update(QDomni=True)
```
...yields...
```
HTTPError: HTTP Error 404: Not Found
```

Tested on [release-0.4.1](https://github.com/spacepy/spacepy/releases/tag/release-0.4.1) and [d8f8a7a](https://github.com/spacepy/spacepy/commit/d8f8a7acdb0e2091df8ea28efba83252d1de0340) (origin/HEAD at time of writing).

Glancing into the issue, (and as noted by Jon in #233 and #338,) ViRBO has been scaling back their hosting obligations.  The default spacepy config cites http://virbo.org/ftp/QinDenton/hour/merged/latest/WGhour-latest.d.zip to download the data, which redirects to http://mag.gmu.edu/ftp/QinDenton/hour/merged/latest/WGhour-latest.d.zip, which gives the 404 error.  In fact, http://mag.gmu.edu appears to be down (or unconfigured,) as it's the default nginx landing page.

The ViRBO page says (just at http://virbo.org),
> The ViRBO project was discontinued in 2014 and these pages are no longer being updated. Feel free to contact rweigel@gmu.edu if any links to information that you are interested in are broken.

I have not contacted rweigel@gmu.edu, but it seems worth a shot.

**Comment by jtniehof** [comment]
See #616 for a workaround for now.

**Comment by asher-m** [comment]
Sigh...thanks.  Wasn't able to find that.
