### ISSUE TITLE
Test failure: test_irbempy.IRBEMBigTests.test_getLstar_T05

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#68]
Error on 64-bit Windows, python 2.7, in getUTC, line 1162 of spacepy time (so this may be a time bug); ultimately "cannot convert float NaN to integer".

Works on 32-bit Windows, python 2.7; 32-bit Windows, Python 3.6; and 64-bit Windows, Python 3.6.

**Comment by jtniehof** [comment]
Notes from #139:
`python test_irbempy.py IRBEMBigTests` fails.
`python test_irbempy.py IRBEMBigTests.test_get_Lstar_T05` succeeds. So it's another preconditioning issue.

The previous one is test_get_Lstar_T01 and `python test_irbempy.py IRBEMBigTests.test_get_Lstar_T01 IRBEMBigTests.test_get_Lstar_T05` fails in T05. `python test_irbempy.py IRBEMBigTests.test_get_Lstar_T05 IRBEMBigTests.test_get_Lstar_T01` succeeds.

So it's not just any L*, it's specifically the T01 seems to set up the T05 for failure.

TB on this is get_omni in setUp, to getUTC in the Ticktock constructor, ultimately to num2date. It's the same off current master (32652a) and in PR #139, which are different IRBEM libraries.

I'm actually encouraged by the fact this is failing in the same place with a different IRBEM library. If it were a truly nasty Heisenbug due to the compiler screwing up or something I'd expect the failure mode to be subtly different.

**Comment by jtniehof** [comment]
MBE (as contrasted with MWE)
```
import spacepy
import spacepy.omni
import spacepy.time
import spacepy.coordinates
import spacepy.irbempy as ib

ticks = spacepy.time.Ticktock(['2001-02-02T12:00:00', '2001-02-02T12:10:00'], 'ISO')
loci = spacepy.coordinates.Coords([[3,0,0],[2,0,0]], 'GEO', 'car')
omnivals = spacepy.omni.get_omni(ticks, dbase='Test')

actual = ib.get_Lstar(ticks, loci, [90], omnivals=omnivals)

ticks = spacepy.time.Ticktock(['2001-02-02T12:00:00', '2001-02-02T12:10:00'], 'ISO')
loci = spacepy.coordinates.Coords([[3,0,0],[2,0,0]], 'GEO', 'car')
omnivals = spacepy.omni.get_omni(ticks, dbase='Test')
```
`get_omni` still fails if `ticks` and `loci` aren't recalculated

**Comment by drsteve** [comment]
So this example fails?
Does that mean that `get_omni` is modifying `ticks`?

Or, as I was originally thinking, is this a problem in `prep_irbem` (or similar) where either `ticks` or `loci` gets modified?

**Comment by jtniehof** [comment]
If I knew what the problem was, I'd fix it :) It's that after the L* call, get_omni fails. This is actually a better example, now that I've narrowed it down:

```
ticks = spacepy.time.Ticktock(['2001-02-02T12:00:00', '2001-02-02T12:10:00'], 'ISO')
loci = spacepy.coordinates.Coords([[3,0,0],[2,0,0]], 'GEO', 'car')
omnivals = spacepy.omni.get_omni(ticks, dbase='Test')
actual = ib.irbempy._get_Lstar(ticks, loci, [90], omnivals=omnivals)

matplotlib.dates.num2date(729936.58)
```

I was going nuts because the multiprocessing made debugging impossible (and I didn't realize multiprocessing was going on.)

**Comment by jtniehof** [comment]
MBE runs with extMag:
T05, 0, MEAD, T87SHORT, T87LONG, T89, OPQUIET, OPDYN, T96, OSTA, 

MBE errors with extMag:
T01STORM, unspecified (T01STORM), T01QUIET, 

Other:
ALEX prints a lot of "GRAND EXP-BESM, X=        NaN" and doesn't return. But this happens on Linux too.
TS07 errors "TS07_DATA_PATH global variable not set" and I don't feel like chasing down the data source there.

If I just call prep_irbem instead of the full Lstar, T01STORM works. So it's not directly in prep_irbem; prep_irbem could still be implicated of course and it's really the only thing different between models.

**Comment by drsteve** [comment]
There's a function in irbempy to retrieve the TS07 input data... but it's probably not worth working through that right now.

Anyway, it's nice to have this one narrowed down, so thanks for digging.

**Comment by jtniehof** [comment]
I'd really like to put this one to bed because it might be indicative of some sort of binary calling mismatch, but I'm running up against the limits of my Fortran.

Usually when we've seen stuff like this in the past, it's been because a function is called with a different set of argument types (or return type) than is in the actual library. E.g. 79324a154232704b9269bc11ca791006fbe5c457 or 516f35a1cd771e7602dfd71a4415ee231f4bef23 . So my "sense of smell" here is that f2py or..something...is not inferring the same calling signature as is going into the real library. It _might_ be related to, weirdly enough, #67 and the "Windows longs are always 32-bit" problem. It might also be related to a mismatch between compiler options between when setup.py builds the library and when f2py runs to build the extension. That I can probably take a bit of a stab at, but it will be a bit of a stab in the dark.

Note this is _not_ necessarily okay on other OS/bitsize; it's just that whatever haywire stack-smashing happens is touching part of the interpreter's memory space we aren't doing anything with.

**Comment by jtniehof** [comment]
FWIW calling AlphaOfK does not make the date2num fail. I've poked at some small perturbations in the time, location, pitch angle with L* on T01 and it's failing pretty consistently, so doesn't seem data-dependent.

**Comment by jtniehof** [comment]
Notes on flailing: tried using wrappers32.inc; tried specifying --f77flags=-m64 --f90flags=-m64. (There's an explicit -m64 for the actual compile of the irbem library.)

**Comment by drsteve** [comment]
I've been in touch with some of the ONERA folks, and they have a new person involved with IRBEM who they've volunteered to help out with SpacePy/IRBEM topics. I would also like this solved, but I'm okay with postponing the fix until after 0.1.7 drops just so we can get a release out. I don't think this is breaking anything new, just failing to fix an existing issue. At that, an existing issue for a Python version (on Windows) that's EOL.

FWIW, I had also done some exploring of compiler flags. I think you might be on the right track with f2py and the 32-bit longs. Hopefully modernizing the Fortran code will help f2py understand what it's wrapping, and we can aim to have a fix in the 0.1.8 release at the end of the year?!

**Comment by jtniehof** [comment]
I think we understand this well enough to believe it's an irbem-wrapping thing not a "compiler completely out to lunch" thing so it should remain fairly isolated. We may want to put a release note regarding it.

Attached are the logs from the build in each env, so we can look for suggestive bits in the diff. To clean up the diff I've done some scrubbing...the temporary directory (tmpksaduf234-like) has been replaced with "TMP" and stuff like win32-amd64-2.7 replaced with "WIN".

[build_py2_32.txt](https://github.com/spacepy/spacepy/files/3287366/build_py2_32.txt)
[build_py2_64.txt](https://github.com/spacepy/spacepy/files/3287367/build_py2_64.txt)
[build_py3_32.txt](https://github.com/spacepy/spacepy/files/3287368/build_py3_32.txt)
[build_py3_64.txt](https://github.com/spacepy/spacepy/files/3287369/build_py3_64.txt)

**Comment by jtniehof** [comment]
There are still some case differences but using xxd and setting case-insensitive is somewhat informative. It does look like f2py behaves very differently on 2 than 3 (maybe not a surprise.)

**Comment by drsteve** [comment]
I can't reproduce under the `py27_64` environment with the latest master...

**Comment by jtniehof** [comment]
Still fails here. Maybe Win7 vs. Win10?

**Comment by jtniehof** [comment]
Windows 7, py38_64 environment, now the minimum is:
`python test_all.py IRBEMBigTests.test_get_Lstar_T01 MakeCDF.testCreateCDFFromSpaceData`
So it's still T01 that's failing but it's stomping on something else.

I mean, the amount we care about Win7 is basically zero, but can you confirm `test_all.py` runs on Win10 without error at some point? I'm going to make this not a blocker for 0.2.2.

**Comment by drsteve** [comment]
Per [the Python 2 EOL plan](https://spacepy.github.io/py2k_eol.html) we're no longer providing fixes for bugs that can't be reproduced using Python 3. And Windows 7 EOL was January 2020...

So can we close this bug as out-of-date?

**Comment by jtniehof** [comment]
Per my last comment it looks like it cropped up on 3.8 as well, but since this has only ever happened on Windows 7, I'm the only one who's seen it, and I've deleted that VM, I think we can close as can't reproduce. The test suite runs fine on Windows 10 with a mess of Python versions.
