### ISSUE TITLE
Pybats QOtree failures for complex AMR arrangements/multiple root blocks

### ISSUE THREAD

**Issue by spacecataz** [spacepy/spacepy#696]
I have found some "edge cases" for QOtree that causes failures. Under complex AMR layouts, it's possible to fool the leaf identification logic such that non leaf blocks are found for non-leaf portions (e.g., portions that should be further refined but are not). This leads to regions with non-uniform grid spacing within a single block. 

### Minimal example to reproduce issue:
This is challenging to reproduce quickly; but physics-based AMR simulations of BATS-R-US can run into this problem reasonably often. Output files associated with this issue are typically quite large.

### Error message/Traceback:
For the leaf identification issue, there is no Exception. Rather, spurious layouts will be created, leading to inaccurate pcolor plots and stream traces. For example, the image below shows a failed leaf block. The black outline shows the block boundaries; the points inside represent locations associated with many different actual leaf blocks.
![qotree_problem](https://github.com/spacepy/spacepy/assets/5991247/9d7d3000-7c13-4e78-bfeb-1176d1313a9a)

### OS, Python version, and dependency version information:
Problem is OS/Python version independent and is a limitation of the current logic within QOTree.

### Version of SpacePy
All versions (development branch) before June 11th, 2023.

**Comment by spacecataz** [comment]
Two comments on the above: 

1. This problem is exacerbated by the fact that BATS allows for multiple root blocks. While this is not commonly used, it can create issues when the number of roots is not a rational factor of the blocksize. There's not an easy fix for this outside drastically rewriting `qtree`.
2. This problem is also exacerbated by the fact that `QTree` assumes a blocksize of 8x8, and this is hard-coded. This should be an easy fix within `spacepy.pybats`.

**Comment by jtniehof** [comment]
Closed in #697.
