### ISSUE TITLE
pybats test fail if test discovered from outside test directory

### ISSUE THREAD

**Issue by balarsen** [spacepy/spacepy#79]
I run tests using pytest from the top level and test_pybats.py fails. 

```
tests/test_pybats.py:116: in <module>
    class TestBats2d(unittest.TestCase):
tests/test_pybats.py:121: in TestBats2d
    mhd = pbs.Bats2d('data/pybats_test/y0_binary.out')
spacepy/pybats/bats.py:633: in __init__
    IdlFile.__init__(self, filename, format=format, keep_case=False)
spacepy/pybats/__init__.py:868: in __init__
    self.read(header, keep_case)   # Read file.
spacepy/pybats/__init__.py:886: in read
    _read_idl_bin(self, header=header, keep_case=keep_case)
spacepy/pybats/__init__.py:589: in _read_idl_bin
    infile = open(pbdat.attrs['file'], 'rb')
E   FileNotFoundError: [Errno 2] No such file or directory: 'data/pybats_test/y0_binary.out'
```

This issue here are the full encoded filenames within test_pybats.py. [L61](https://github.com/spacepy/spacepy/blob/00b16984a9a62e37996961e1fcf782256fb7b6c2/tests/test_pybats.py#L61), [L76](https://github.com/spacepy/spacepy/blob/00b16984a9a62e37996961e1fcf782256fb7b6c2/tests/test_pybats.py#L76),  [L95](https://github.com/spacepy/spacepy/blob/00b16984a9a62e37996961e1fcf782256fb7b6c2/tests/test_pybats.py#L95), and [L104](https://github.com/spacepy/spacepy/blob/00b16984a9a62e37996961e1fcf782256fb7b6c2/tests/test_pybats.py#L104) to name a few. These likely need to be updated with something like:

`os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'pybats_test', 'y0_binary.out')`

**Comment by drsteve** [comment]
Redundant. See #178

**Comment by balarsen** [comment]
Except this pull was piñata which is not in the other. Didn’t learn about
all the files till after this one.
