### ISSUE TITLE
Spacepy fails to install in Python 3.7 using pip3

### ISSUE THREAD

**Issue by Rhyst223** [spacepy/spacepy#92]
I have attempted to install Spacepy on Python 3.7 using pip3 with the following, and have all of the dependencies already installed

### Minimal example to reproduce issue:

```
pip3 install spacepy
```
but it fails to build the spacepy wheel and produces the following error
### Error message/Traceback:

```
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/w2/m4t8qtjn1td5rpn1ntyflrnc0000gn/T/pip-install-uypunchh/spacepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/w2/m4t8qtjn1td5rpn1ntyflrnc0000gn/T/pip-record-oq8bbtle/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/w2/m4t8qtjn1td5rpn1ntyflrnc0000gn/T/pip-install-uypunchh/spacepy/
```
Any idea what's going on?

### OS, Python version, and dependency version information:

I am running on macOS Mojave 10.14.3, Python 3.7.

**Comment by drsteve** [comment]
Thanks for the report!

I'll admit that I'm rarely a Mac user and I can't test this on Mac. My first guess is that this is a C/Fortran compiler issue though. We do test (using Travis CI) under Python 3.7, and in that test environment we install all prerequisites then clone the git repository and build/install. That's passing, but it's also on a clean Ubuntu container.

Can I ask for some extra info?
- The path to the Python interpreter suggests that you're using Homebrew. Is that right?
  - Do you know what C and Fortran compiler versions you have installed?
- Was there more output from pip prior to the final error message you pasted in here? Can I ask you to paste that too?
- What's the output of: `pip --version`, `python --version`, `python -c "import numpy; print(numpy.version.version)`?

Finally, if you grab the source code from this git repo (`git clone https://github.com/spacepy/spacepy.git`), are you able to build spacepy? (`python setup.py install --user`)

Hopefully that'll help us narrow this down. I'm going to tag @balarsen as our main Mac user and @jtniehof as the installer guru in case they have better ideas.

**Comment by balarsen** [comment]
Just to check, did you reinstall macports after upgrading to Mohave?

**Comment by jtniehof** [comment]
It should also be possible to try installing from git master without downloading at all: `pip install git+https://github.com/spacepy/spacepy.git`

0.1.6 not installing on Python 3.7 would not surprise me. Time for release engineering, as it's been for awhile.

**Comment by Rhyst223** [comment]
Thanks for the reply. In the response to the first message I have the following extra information:

pip3 version: `pip 19.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

pip version:  `pip 19.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

python version: `python 2.7.15`

python3 version: `python 3.7.2`

numpy version: 1.16.1

I am using homebrew, and I belive I do not have MacPorts installed. The C and Fortran compilers I believe are gcc and gfortran. `gcc --version' yields:
```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
and `gfortran --version` yields:
`GNU Fortran (Homebrew GCC 8.2.0) 8.2.0`

When I download the git clone ad try to install as suggested I receive the following output:
```
running install
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

The output from pip3 prior to the failed wheel build is as follows:
    ```
File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['f2py3.7', '--overwrite-signature', '-m', 'irbempylib', '-h', 'irbempylib.pyf', 'source/onera_desp_lib.f', 'source/CoordTrans.f', 'source/AE8_AP8.f', 'source/find_foot.f', 'source/drift_bounce_orbit.f', 'only:', 'make_lstar1', 'make_lstar_shell_splitting1', 'find_foot_point1', 'coord_trans1', 'find_magequator1', 'find_mirror_point1', 'get_field1', 'get_ae8_ap8_flux', 'fly_in_nasa_aeap1', 'trace_field_line2_1', 'trace_field_line_towards_earth1', 'trace_drift_bounce_orbit', ':']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for spacepy
```
There is much more from the output but I think this is the error which causes the problem

**Comment by jtniehof** [comment]
Thanks for the info! Based on your numpy version, you're being bit by #90, which is probably a bug in numpy 1.16.0 and 1.16.1 (and that's supported by your pip3 output).

Also, it wouldn't help in this case, but the message `can't combine user with prefix, exec_prefix/home, or install_(plat)base` suggests the command line `python setup.py install --user` wasn't entered exactly as suggested...it would be good to have the exact command line that gave that error just in case.

**Comment by Rhyst223** [comment]
Do you know which numpy version to downgrade to? I just tried `numpy 1.15.4` but then the f2py folders are removed.

To get over the prefix issue I had to use
`python setup.py install --user --prefix=`

and it seemed to allow it to run, but the build still fails!

**Comment by jtniehof** [comment]
1.15.4 should work. Which f2py folders are removed?

If you're specifying a `--prefix`, don't use `--user`.

**Comment by Rhyst223** [comment]
If I downgrade to numpy 1.15.4 and then run `pip3 install spacepy` it fails with the following output:

```
  creating build/lib
  creating build/lib/spacepy
  clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk build/temp.macosx-10.14-x86_64-3.7/spacepy/libspacepy/toolbox.o build/temp.macosx-10.14-x86_64-3.7/spacepy/libspacepy/randomkit.o build/temp.macosx-10.14-x86_64-3.7/spacepy/libspacepy/cn_solver.o build/temp.macosx-10.14-x86_64-3.7/spacepy/libspacepy/ctrace2d.o build/temp.macosx-10.14-x86_64-3.7/spacepy/libspacepy/poppy.o -lm -o build/lib/spacepy/libspacepy.so
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  customize Gnu95FCompiler
  Found executable /usr/local/bin/gfortran
  Found executable /usr/bin/ar
  Found executable /usr/bin/ranlib
  error: [Errno 13] Permission denied: 'f2py'
```

**Comment by Rhyst223** [comment]
Donwgrading to numpy 1.15.4 removes the following `f2py` folders:

```
/usr/local/bin/f2py
/usr/local/bin/f2py3
/usr/local/bin/f2py3.7
```

**Comment by jtniehof** [comment]
Those shouldn't be folders, but files. You're installing Python via homebrew; were you doing numpy via homebrew as well, or via pip? Some googling indicates the possibility of f2py not getting execute permissions set ([e.g. here](https://stackoverflow.com/questions/26746620/how-to-run-f2py-in-macosx)) but if it's not there at all, that's very strange.

This is reaching the limits of my mac remote troubleshooting abilities. Brian might have better ideas. If you're not able to run "f2py" at a terminal and get back something, the chances of SpacePy being able to find something are pretty small.

I'm going to leave this open for now in case it's something where f2py is properly installed and hiding somewhere, and we can tweak the installer to make life better, but this is sounding like a brew and/or pip problem.

**Comment by Rhyst223** [comment]
Okay so I have managed to build spacepy now and it has imported into spyder without error!

It was all to do with the permissions on `f2py`, so I just ran

`chmod 755 /usr/local/bin/f2py`
`pip3 install spacepy`

and all worked fine. This was also using `numpy 1.15.4`

**Comment by jtniehof** [comment]
Fantastic! Thanks for pushing through. We'll keep the permissions in mind as a thing to check if this comes up for anyone else.
