### ISSUE TITLE
Cannot import LANLstar although ffnet is installed

### ISSUE THREAD

**Issue by Rhyst223** [spacepy/spacepy#99]
My issue is ...
I finally managed to get spacepy to install on my Mac and it imports fine, however if I run the following
### Minimal example to reproduce issue:

```
from spacepy import LANLstar
```
I get the following error
### Error message/Traceback:

```
Traceback (most recent call last):

  File "<ipython-input-4-3b72e6b6e0f6>", line 1, in <module>
    from spacepy import LANLstar

  File "/usr/local/lib/python3.7/site-packages/spacepy/LANLstar.py", line 32, in <module>
    'LANLstar requires ffnet (http://ffnet.sourceforge.net/)')

RuntimeError: LANLstar requires ffnet (http://ffnet.sourceforge.net/)
```
But I already have ffnet installed through the `pip3 install spacepy` in the directory:
`/usr/local/lib/python3.7/site-packages/ffnet`

But with this in mind, if I simply run `import ffnet` I get the following error:

```
Traceback (most recent call last):

  File "<ipython-input-5-6802228c8f9c>", line 1, in <module>
    import ffnet

  File "/Users/rlt1917/Library/Python/3.7/lib/python/site-packages/ffnet/__init__.py", line 16, in <module>
    import ffnet.fortran as fortran

  File "/Users/rlt1917/Library/Python/3.7/lib/python/site-packages/ffnet/fortran/__init__.py", line 14, in <module>
    from . import _ffnet, _pikaia

ImportError: dlopen(/Users/rlt1917/Library/Python/3.7/lib/python/site-packages/ffnet/fortran/_ffnet.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
  Referenced from: /Users/rlt1917/Library/Python/3.7/lib/python/site-packages/ffnet/fortran/_ffnet.cpython-37m-darwin.so
  Reason: image not found
```

Does anybody know what this could be?

I am running on Python 3.7 on Mac with the most recent Mojave, with the most recent GCC installed with Homebrew

**Comment by jtniehof** [comment]
That means ffnet didn't install. If you installed it before you got the f2py situation straightened out, try uninstalling and reinstalling ffnet (just itself.)

**Comment by Rhyst223** [comment]
I have just tried that and it has still failed. could it be anything to do with where `gfortran` is located since ffnet uses the fortran compiler?

It was installed with Homebrew  but I have also seen the following

```
which gfortran
/usr/local/bin/gfortran
which gcc
/usr/bin/gcc
```

Should they be in different places?

**Comment by jtniehof** [comment]
It seems evident this isn't a SpacePy bug since ffnet isn't successfully installed. I don't have any further guesses on what might be the issue. The ffnet support page is [here](https://sourceforge.net/projects/ffnet/support).

I'll leave this open for a few days in case people have suggestions.

**Comment by Rhyst223** [comment]
I agree, I now think it is definitely a fortran compiler issue (more specifically the recent version of `gcc` in homebrew), since if I attempt to build through the git clone I receive the following output

```
Compiler /usr/local/bin/gfortran failed, trying another
Compiler gfortran failed, trying another
irbemlib compile failed. Try a different Fortran compiler? (--fcompiler)
```

Possibly linked to https://github.com/spacepy/spacepy/issues/41 perhaps?

**Comment by Rhyst223** [comment]
Fixed the issue! For anyone having the same issue simply install gcc-7 with
`brew install gcc@7`
navigate to the directory
`/usr/local/opt/gcc/lib/gcc@7`
and copy the folder called `7`. Then navigate to
`/usr/local/opt/gcc/lib/gcc`
and paste in the folder and all should work.

**Comment by jtniehof** [comment]
Cool. Thanks for sharing the fix.
